"""initial_database_schema

Revision ID: 1577bd1ae513
Revises: 
Create Date: 2025-07-22 17:54:28.371782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1577bd1ae513'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create schemas first
    op.execute('CREATE SCHEMA IF NOT EXISTS auth')
    op.execute('CREATE SCHEMA IF NOT EXISTS automation')
    op.execute('CREATE SCHEMA IF NOT EXISTS data_integration')
    op.execute('CREATE SCHEMA IF NOT EXISTS jobs')
    op.execute('CREATE SCHEMA IF NOT EXISTS data_objects')
    op.execute('CREATE SCHEMA IF NOT EXISTS analysis')
    op.execute('CREATE SCHEMA IF NOT EXISTS chat')
    op.execute('CREATE SCHEMA IF NOT EXISTS project')
    op.execute('CREATE SCHEMA IF NOT EXISTS node')
    op.execute('CREATE SCHEMA IF NOT EXISTS model_integration')

    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('disabled', sa.Boolean(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    schema='auth'
                    )
    op.create_table('automation',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='automation'
                    )
    op.create_table('function',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('script_path', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='automation'
                    )
    op.create_table('modality',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='automation'
                    )
    op.create_table('programming_language',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='automation'
                    )
    op.create_table('source',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='automation'
                    )
    op.create_table('task',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='automation'
                    )
    op.create_table('feature',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('unit', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('subtype', sa.String(), nullable=False),
                    sa.Column('scale', sa.String(), nullable=False),
                    sa.Column('source', sa.String(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('name'),
                    schema='data_objects'
                    )
    op.create_table('user_api_keys',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('key', sa.String(), nullable=False),
                    sa.Column('expires_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('key'),
                    schema='auth'
                    )
    op.create_table('function_input_structure',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('structure_id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('required', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "structure_id IN ('time_series', 'time_series_aggregation')"),
                    sa.ForeignKeyConstraint(
                        ['function_id'], ['automation.function.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='automation'
                    )
    op.create_table('function_output_structure',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('structure_id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "structure_id IN ('time_series', 'time_series_aggregation')"),
                    sa.ForeignKeyConstraint(
                        ['function_id'], ['automation.function.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='automation'
                    )
    op.create_table('programming_language_version',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('programming_language_id',
                              sa.UUID(), nullable=False),
                    sa.Column('version', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['programming_language_id'], [
                        'automation.programming_language.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='automation'
                    )
    op.create_table('local_directory_data_source',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('directory_name', sa.String(), nullable=False),
                    sa.Column('save_path', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='data_integration'
                    )
    op.create_table('dataset',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('modality', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='data_objects'
                    )
    op.create_table('project',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='project'
                    )
    op.create_table('model',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('owner_id', sa.UUID(), nullable=False),
                    sa.Column('public', sa.Boolean(), nullable=False),
                    sa.Column('modality_id', sa.UUID(), nullable=False),
                    sa.Column('source_id', sa.UUID(), nullable=False),
                    sa.Column('programming_language_version_id',
                              sa.UUID(), nullable=False),
                    sa.Column('setup_script_path',
                              sa.String(), nullable=False),
                    sa.Column('config_script_path',
                              sa.String(), nullable=False),
                    sa.Column('input_description',
                              sa.String(), nullable=False),
                    sa.Column('output_description',
                              sa.String(), nullable=False),
                    sa.Column('config_parameters', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['modality_id'], ['automation.modality.id'], ),
                    sa.ForeignKeyConstraint(['owner_id'], ['auth.users.id'], ),
                    sa.ForeignKeyConstraint(['programming_language_version_id'], [
                        'automation.programming_language_version.id'], ),
                    sa.ForeignKeyConstraint(
                        ['source_id'], ['automation.source.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='automation'
                    )
    op.create_table('context',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['project.project.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='chat'
                    )
    op.create_table('conversation',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['project.project.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='chat'
                    )
    op.create_table('local_directory_file',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('directory_id', sa.UUID(), nullable=False),
                    sa.Column('file_name', sa.String(), nullable=False),
                    sa.Column('file_path', sa.String(), nullable=False),
                    sa.Column('file_type', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['directory_id'], ['data_integration.local_directory_data_source.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='data_integration'
                    )
    op.create_table('object_group',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('original_id_name', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('role', sa.String(), nullable=False),
                    sa.Column('structure_type', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "structure_type IN ('time_series', 'time_series_aggregation')"),
                    sa.ForeignKeyConstraint(
                        ['dataset_id'], ['data_objects.dataset.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='data_objects'
                    )
    op.create_table('node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('x_position', sa.Float(), nullable=False),
                    sa.Column('y_position', sa.Float(), nullable=False),
                    sa.Column('type', sa.String(length=255), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['project.project.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='node'
                    )
    op.create_table('project_automation',
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('automation_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['project.project.id'], ),
                    sa.PrimaryKeyConstraint('project_id', 'automation_id'),
                    schema='project'
                    )
    op.create_table('project_dataset',
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['dataset_id'], ['data_objects.dataset.id'], ),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['project.project.id'], ),
                    sa.PrimaryKeyConstraint('project_id', 'dataset_id'),
                    schema='project'
                    )
    op.create_table('model_task',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('model_id', sa.UUID(), nullable=False),
                    sa.Column('task_id', sa.UUID(), nullable=False),
                    sa.Column('inference_script_path',
                              sa.String(), nullable=False),
                    sa.Column('training_script_path',
                              sa.String(), nullable=False),
                    sa.Column('inference_function_id',
                              sa.UUID(), nullable=False),
                    sa.Column('training_function_id',
                              sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['inference_function_id'], [
                        'automation.function.id'], ),
                    sa.ForeignKeyConstraint(
                        ['model_id'], ['automation.model.id'], ),
                    sa.ForeignKeyConstraint(
                        ['task_id'], ['automation.task.id'], ),
                    sa.ForeignKeyConstraint(['training_function_id'], [
                        'automation.function.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='automation'
                    )
    op.create_table('automation_context',
                    sa.Column('context_id', sa.UUID(), nullable=False),
                    sa.Column('automation_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['automation_id'], ['automation.automation.id'], ),
                    sa.ForeignKeyConstraint(
                        ['context_id'], ['chat.context.id'], ),
                    sa.PrimaryKeyConstraint('context_id', 'automation_id'),
                    schema='chat'
                    )
    op.create_table('chat_message',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('conversation_id', sa.UUID(), nullable=False),
                    sa.Column('role', sa.String(), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('job_id', sa.UUID(), nullable=True),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('context_id', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['context_id'], ['chat.context.id'], ),
                    sa.ForeignKeyConstraint(['conversation_id'], [
                        'chat.conversation.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='chat'
                    )
    op.create_table('conversation_mode',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('conversation_id', sa.UUID(), nullable=False),
                    sa.Column('mode', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['conversation_id'], [
                        'chat.conversation.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='chat'
                    )
    op.create_table('dataset_context',
                    sa.Column('context_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['context_id'], ['chat.context.id'], ),
                    sa.ForeignKeyConstraint(
                        ['dataset_id'], ['data_objects.dataset.id'], ),
                    sa.PrimaryKeyConstraint('context_id', 'dataset_id'),
                    schema='chat'
                    )
    op.create_table('pydantic_message',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('conversation_id', sa.UUID(), nullable=False),
                    sa.Column('message_list', postgresql.BYTEA(),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['conversation_id'], [
                        'chat.conversation.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='chat'
                    )
    op.create_table('data_object',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('group_id', sa.UUID(), nullable=True),
                    sa.Column('original_id', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('additional_variables', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "additional_variables IS NULL OR jsonb_typeof(additional_variables) = 'object'"),
                    sa.ForeignKeyConstraint(
                        ['group_id'], ['data_objects.object_group.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='data_objects'
                    )
    op.create_table('feature_in_group',
                    sa.Column('group_id', sa.UUID(), nullable=False),
                    sa.Column('feature_name', sa.String(), nullable=False),
                    sa.Column('source', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint("source IN ('data', 'metadata')"),
                    sa.ForeignKeyConstraint(
                        ['feature_name'], ['data_objects.feature.name'], ),
                    sa.ForeignKeyConstraint(
                        ['group_id'], ['data_objects.object_group.id'], ),
                    sa.PrimaryKeyConstraint('group_id', 'feature_name'),
                    schema='data_objects'
                    )
    op.create_table('job',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('conversation_id', sa.UUID(), nullable=True),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('started_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('completed_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('job_name', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['conversation_id'], [
                        'chat.conversation.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='jobs'
                    )
    op.create_table('automation_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('automation_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['automation_id'], ['automation.automation.id'], ),
                    sa.ForeignKeyConstraint(['id'], ['node.node.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='node'
                    )
    op.create_table('dataset_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['dataset_id'], ['data_objects.dataset.id'], ),
                    sa.ForeignKeyConstraint(['id'], ['node.node.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='node'
                    )
    op.create_table('analysis_jobs_automations',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('job_id', sa.UUID(), nullable=False),
                    sa.Column('automation_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['automation_id'], ['automation.automation.id'], ),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='analysis'
                    )
    op.create_table('analysis_jobs_datasets',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('job_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['dataset_id'], ['data_objects.dataset.id'], ),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='analysis'
                    )
    op.create_table('analysis_jobs_results',
                    sa.Column('job_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('number_of_datasets',
                              sa.Integer(), nullable=False),
                    sa.Column('number_of_automations',
                              sa.Integer(), nullable=False),
                    sa.Column('analysis_plan', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('pdf_created', sa.Boolean(), nullable=False),
                    sa.Column('pdf_s3_path', sa.String(), nullable=True),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
                    sa.PrimaryKeyConstraint('job_id'),
                    schema='analysis'
                    )
    op.create_table('analysis_status_messages',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('job_id', sa.UUID(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('message', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='analysis'
                    )
    op.create_table('data_object_computed_from_function',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('data_object_id', sa.UUID(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['data_object_id'], [
                        'data_objects.data_object.id'], ),
                    sa.ForeignKeyConstraint(
                        ['function_id'], ['automation.function.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='automation'
                    )
    op.create_table('data_integration_job_local_input',
                    sa.Column('job_id', sa.UUID(), nullable=False),
                    sa.Column('target_dataset_description',
                              sa.String(), nullable=False),
                    sa.Column('directory_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['directory_id'], ['data_integration.local_directory_data_source.id'], ),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job.id'], ),
                    sa.PrimaryKeyConstraint('job_id'),
                    schema='data_integration'
                    )
    op.create_table('data_integration_job_result',
                    sa.Column('job_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('code_explanation', sa.String(), nullable=False),
                    sa.Column('python_code_path', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job.id'], ),
                    sa.PrimaryKeyConstraint('job_id'),
                    schema='data_integration'
                    )
    op.create_table('derived_object_source',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('derived_object_id', sa.UUID(), nullable=False),
                    sa.Column('original_object_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['derived_object_id'], [
                        'data_objects.data_object.id'], ),
                    sa.ForeignKeyConstraint(
                        ['id'], ['data_objects.data_object.id'], ),
                    sa.ForeignKeyConstraint(['original_object_id'], [
                        'data_objects.data_object.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='data_objects'
                    )
    op.create_table('time_series',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('num_timestamps', sa.Integer(), nullable=False),
                    sa.Column('start_timestamp', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('end_timestamp', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('sampling_frequency',
                              sa.String(), nullable=False),
                    sa.Column('timezone', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['id'], ['data_objects.data_object.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='data_objects'
                    )
    op.create_table('time_series_aggregation',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('is_multi_series_computation',
                              sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['id'], ['data_objects.data_object.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='data_objects'
                    )
    op.create_table('model_integration_job_input',
                    sa.Column('job_id', sa.UUID(), nullable=False),
                    sa.Column('model_id_str', sa.String(), nullable=False),
                    sa.Column('source', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job.id'], ),
                    sa.PrimaryKeyConstraint('job_id'),
                    schema='model_integration'
                    )
    op.create_table('model_integration_job_result',
                    sa.Column('job_id', sa.UUID(), nullable=False),
                    sa.Column('model_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['jobs.job.id'], ),
                    sa.PrimaryKeyConstraint('job_id'),
                    schema='model_integration'
                    )
    op.create_table('analysis_context',
                    sa.Column('context_id', sa.UUID(), nullable=False),
                    sa.Column('analysis_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['analysis_id'], ['analysis.analysis_jobs_results.job_id'], ),
                    sa.ForeignKeyConstraint(
                        ['context_id'], ['chat.context.id'], ),
                    sa.PrimaryKeyConstraint('context_id', 'analysis_id'),
                    schema='chat'
                    )
    op.create_table('time_series_aggregation_input',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('time_series_id', sa.UUID(), nullable=False),
                    sa.Column('aggregation_id', sa.UUID(), nullable=False),
                    sa.Column('input_feature_name',
                              sa.String(), nullable=False),
                    sa.Column('start_timestamp', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('end_timestamp', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint('start_timestamp < end_timestamp'),
                    sa.ForeignKeyConstraint(['aggregation_id'], [
                        'data_objects.time_series_aggregation.id'], ),
                    sa.ForeignKeyConstraint(
                        ['id'], ['data_objects.data_object.id'], ),
                    sa.ForeignKeyConstraint(['time_series_id'], [
                        'data_objects.time_series.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='data_objects'
                    )
    op.create_table('analysis_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['analysis_id'], ['analysis.analysis_jobs_results.job_id'], ),
                    sa.ForeignKeyConstraint(['id'], ['node.node.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='node'
                    )
    op.create_table('project_analysis',
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('analysis_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['analysis_id'], ['analysis.analysis_jobs_results.job_id'], ),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['project.project.id'], ),
                    sa.PrimaryKeyConstraint('project_id', 'analysis_id'),
                    schema='project'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_analysis', schema='project')
    op.drop_table('analysis_node', schema='node')
    op.drop_table('time_series_aggregation_input', schema='data_objects')
    op.drop_table('analysis_context', schema='chat')
    op.drop_table('model_integration_job_result', schema='model_integration')
    op.drop_table('model_integration_job_input', schema='model_integration')
    op.drop_table('time_series_aggregation', schema='data_objects')
    op.drop_table('time_series', schema='data_objects')
    op.drop_table('derived_object_source', schema='data_objects')
    op.drop_table('data_integration_job_result', schema='data_integration')
    op.drop_table('data_integration_job_local_input',
                  schema='data_integration')
    op.drop_table('data_object_computed_from_function', schema='automation')
    op.drop_table('analysis_status_messages', schema='analysis')
    op.drop_table('analysis_jobs_results', schema='analysis')
    op.drop_table('analysis_jobs_datasets', schema='analysis')
    op.drop_table('analysis_jobs_automations', schema='analysis')
    op.drop_table('dataset_node', schema='node')
    op.drop_table('automation_node', schema='node')
    op.drop_table('job', schema='jobs')
    op.drop_table('feature_in_group', schema='data_objects')
    op.drop_table('data_object', schema='data_objects')
    op.drop_table('pydantic_message', schema='chat')
    op.drop_table('dataset_context', schema='chat')
    op.drop_table('conversation_mode', schema='chat')
    op.drop_table('chat_message', schema='chat')
    op.drop_table('automation_context', schema='chat')
    op.drop_table('model_task', schema='automation')
    op.drop_table('project_dataset', schema='project')
    op.drop_table('project_automation', schema='project')
    op.drop_table('node', schema='node')
    op.drop_table('object_group', schema='data_objects')
    op.drop_table('local_directory_file', schema='data_integration')
    op.drop_table('conversation', schema='chat')
    op.drop_table('context', schema='chat')
    op.drop_table('model', schema='automation')
    op.drop_table('project', schema='project')
    op.drop_table('dataset', schema='data_objects')
    op.drop_table('local_directory_data_source', schema='data_integration')
    op.drop_table('programming_language_version', schema='automation')
    op.drop_table('function_output_structure', schema='automation')
    op.drop_table('function_input_structure', schema='automation')
    op.drop_table('user_api_keys', schema='auth')
    op.drop_table('feature', schema='data_objects')
    op.drop_table('task', schema='automation')
    op.drop_table('source', schema='automation')
    op.drop_table('programming_language', schema='automation')
    op.drop_table('modality', schema='automation')
    op.drop_table('function', schema='automation')
    op.drop_table('automation', schema='automation')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
