"""add_pipeline_models

Revision ID: 170d75a6bcd0
Revises: eb77ea7c5cdf
Create Date: 2025-08-20 10:31:16.700118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

from synesis_api.secrets import EMBEDDING_DIM

# revision identifiers, used by Alembic.
revision: str = '170d75a6bcd0'
down_revision: Union[str, None] = 'b986ba738089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('function',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('embedding', Vector(
                        dim=EMBEDDING_DIM), nullable=False),
                    sa.Column('implementation_script_path',
                              sa.String(), nullable=False),
                    sa.Column('setup_script_path',
                              sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='pipeline'
                    )
    op.create_table('modality',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='pipeline'
                    )
    op.create_table('pipeline',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='pipeline'
                    )
    op.create_table('programming_language',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='pipeline'
                    )
    op.create_table('source',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='pipeline'
                    )
    op.create_table('task',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='pipeline'
                    )
    op.create_table('function_input',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('structure_id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('required', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "structure_id IN ('time_series', 'time_series_aggregation')"),
                    sa.ForeignKeyConstraint(
                        ['function_id'], ['pipeline.function.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='pipeline'
                    )
    op.create_table('function_output',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('structure_id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "structure_id IN ('time_series', 'time_series_aggregation')"),
                    sa.ForeignKeyConstraint(
                        ['function_id'], ['pipeline.function.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='pipeline'
                    )
    op.create_table('programming_language_version',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('programming_language_id',
                              sa.UUID(), nullable=False),
                    sa.Column('version', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['programming_language_id'], [
                        'pipeline.programming_language.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='pipeline'
                    )
    op.create_table('model',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('owner_id', sa.UUID(), nullable=False),
                    sa.Column('public', sa.Boolean(), nullable=False),
                    sa.Column('modality_id', sa.UUID(), nullable=False),
                    sa.Column('source_id', sa.UUID(), nullable=False),
                    sa.Column('programming_language_version_id',
                              sa.UUID(), nullable=False),
                    sa.Column('setup_script_path',
                              sa.String(), nullable=False),
                    sa.Column('config_script_path',
                              sa.String(), nullable=False),
                    sa.Column('input_description',
                              sa.String(), nullable=False),
                    sa.Column('output_description',
                              sa.String(), nullable=False),
                    sa.Column('config_parameters', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['modality_id'], ['pipeline.modality.id'], ),
                    sa.ForeignKeyConstraint(['owner_id'], ['auth.users.id'], ),
                    sa.ForeignKeyConstraint(['programming_language_version_id'], [
                        'pipeline.programming_language_version.id'], ),
                    sa.ForeignKeyConstraint(
                        ['source_id'], ['pipeline.source.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='pipeline'
                    )
    op.create_table('model_task',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('model_id', sa.UUID(), nullable=False),
                    sa.Column('task_id', sa.UUID(), nullable=False),
                    sa.Column('inference_script_path',
                              sa.String(), nullable=False),
                    sa.Column('training_script_path',
                              sa.String(), nullable=False),
                    sa.Column('inference_function_id',
                              sa.UUID(), nullable=False),
                    sa.Column('training_function_id',
                              sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['inference_function_id'], [
                        'pipeline.function.id'], ),
                    sa.ForeignKeyConstraint(
                        ['model_id'], ['pipeline.model.id'], ),
                    sa.ForeignKeyConstraint(
                        ['task_id'], ['pipeline.task.id'], ),
                    sa.ForeignKeyConstraint(['training_function_id'], [
                        'pipeline.function.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='pipeline'
                    )
    op.create_table('data_object_computed_from_function',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('data_object_id', sa.UUID(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['data_object_id'], [
                        'data_objects.data_object.id'], ),
                    sa.ForeignKeyConstraint(
                        ['function_id'], ['pipeline.function.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='pipeline'
                    )
    op.drop_constraint('analysis_jobs_automations_automation_id_fkey',
                       'analysis_jobs_automations', schema='analysis', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_jobs_automations', 'pipeline', [
                          'automation_id'], ['id'], source_schema='analysis', referent_schema='pipeline')
    op.drop_constraint('automation_node_automation_id_fkey',
                       'automation_node', schema='node', type_='foreignkey')
    op.create_foreign_key(None, 'automation_node', 'pipeline', ['automation_id'], [
                          'id'], source_schema='node', referent_schema='pipeline')
    op.drop_constraint('automation_context_automation_id_fkey',
                       'automation_context', schema='orchestrator', type_='foreignkey')
    op.create_foreign_key(None, 'automation_context', 'pipeline', ['automation_id'], [
                          'id'], source_schema='orchestrator', referent_schema='pipeline')
    op.create_foreign_key(None, 'project_automation', 'pipeline', ['automation_id'], [
                          'id'], source_schema='project', referent_schema='pipeline')
    op.drop_constraint('model_integration_run_result_model_id_fkey',
                       'model_integration_run_result', schema='runs', type_='foreignkey')
    op.create_foreign_key(None, 'model_integration_run_result', 'model', [
                          'model_id'], ['id'], source_schema='runs', referent_schema='pipeline')
    op.add_column('run', sa.Column('parent_run_id',
                  sa.UUID(), nullable=True), schema='runs')
    op.create_foreign_key(None, 'run', 'run', ['parent_run_id'], [
                          'id'], source_schema='runs', referent_schema='runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'run', schema='runs', type_='foreignkey')
    op.drop_column('run', 'parent_run_id', schema='runs')
    op.drop_constraint(None, 'model_integration_run_result',
                       schema='runs', type_='foreignkey')
    op.create_foreign_key('model_integration_run_result_model_id_fkey', 'model_integration_run_result', 'model', [
                          'model_id'], ['id'], source_schema='runs', referent_schema='automation')
    op.drop_constraint(None, 'project_automation',
                       schema='project', type_='foreignkey')
    op.drop_constraint(None, 'automation_context',
                       schema='orchestrator', type_='foreignkey')
    op.create_foreign_key('automation_context_automation_id_fkey', 'automation_context', 'automation', [
                          'automation_id'], ['id'], source_schema='orchestrator', referent_schema='automation')
    op.drop_constraint(None, 'automation_node',
                       schema='node', type_='foreignkey')
    op.create_foreign_key('automation_node_automation_id_fkey', 'automation_node', 'automation', [
                          'automation_id'], ['id'], source_schema='node', referent_schema='automation')
    op.drop_constraint(None, 'analysis_jobs_automations',
                       schema='analysis', type_='foreignkey')
    op.create_foreign_key('analysis_jobs_automations_automation_id_fkey', 'analysis_jobs_automations', 'automation', [
                          'automation_id'], ['id'], source_schema='analysis', referent_schema='automation')
    op.drop_table('data_object_computed_from_function', schema='pipeline')
    op.drop_table('model_task', schema='pipeline')
    op.drop_table('model', schema='pipeline')
    op.drop_table('programming_language_version', schema='pipeline')
    op.drop_table('function_output', schema='pipeline')
    op.drop_table('function_input', schema='pipeline')
    op.drop_table('task', schema='pipeline')
    op.drop_table('source', schema='pipeline')
    op.drop_table('programming_language', schema='pipeline')
    op.drop_table('pipeline', schema='pipeline')
    op.drop_table('modality', schema='pipeline')
    op.drop_table('function', schema='pipeline')
    # ### end Alembic commands ###
