"""add_project_data_source_table

Revision ID: 463353338d1a
Revises: a94fbd27b757
Create Date: 2025-07-25 15:23:29.004024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463353338d1a'
down_revision: Union[str, None] = 'a94fbd27b757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_integration.data_source.id'], ),
    sa.ForeignKeyConstraint(['id'], ['node.node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='node'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_source_node', schema='node')
    # ### end Alembic commands ###
