"""Rename full name to name

Revision ID: 63c865e3ffd9
Revises: 2cd1e68c9e03
Create Date: 2025-03-15 16:18:49.632382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c865e3ffd9'
down_revision: Union[str, None] = '2cd1e68c9e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name', new_column_name='name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name', new_column_name='full_name')
    # ### end Alembic commands ###
