"""update_data_integration_models

Revision ID: 90e4ee9b3071
Revises: 1577bd1ae513
Create Date: 2025-07-23 13:00:28.456995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90e4ee9b3071'
down_revision: Union[str, None] = '1577bd1ae513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type IN ('local_directory')"),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='data_integration'
    )
    op.create_table('data_integration_job_input',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('target_dataset_description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job.id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    schema='data_integration'
    )
    op.create_table('data_source_in_integration_job',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_integration.data_source.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job.id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    schema='data_integration'
    )
    op.drop_table('data_integration_job_local_input', schema='data_integration')
    op.drop_constraint('local_directory_data_source_user_id_fkey', 'local_directory_data_source', schema='data_integration', type_='foreignkey')
    op.create_foreign_key(None, 'local_directory_data_source', 'data_source', ['id'], ['id'], source_schema='data_integration', referent_schema='data_integration')
    op.drop_column('local_directory_data_source', 'created_at', schema='data_integration')
    op.drop_column('local_directory_data_source', 'description', schema='data_integration')
    op.drop_column('local_directory_data_source', 'user_id', schema='data_integration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('local_directory_data_source', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False), schema='data_integration')
    op.add_column('local_directory_data_source', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True), schema='data_integration')
    op.add_column('local_directory_data_source', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False), schema='data_integration')
    op.drop_constraint(None, 'local_directory_data_source', schema='data_integration', type_='foreignkey')
    op.create_foreign_key('local_directory_data_source_user_id_fkey', 'local_directory_data_source', 'users', ['user_id'], ['id'], source_schema='data_integration', referent_schema='auth')
    op.create_table('data_integration_job_local_input',
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_dataset_description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('directory_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['directory_id'], ['data_integration.local_directory_data_source.id'], name='data_integration_job_local_input_directory_id_fkey'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job.id'], name='data_integration_job_local_input_job_id_fkey'),
    sa.PrimaryKeyConstraint('job_id', name='data_integration_job_local_input_pkey'),
    schema='data_integration'
    )
    op.drop_table('data_source_in_integration_job', schema='data_integration')
    op.drop_table('data_integration_job_input', schema='data_integration')
    op.drop_table('data_source', schema='data_integration')
    # ### end Alembic commands ###
