"""node structure added

Revision ID: a859ce613d67
Revises: b379de9583c5
Create Date: 2025-06-17 15:31:24.079696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a859ce613d67'
down_revision: Union[str, None] = 'b379de9583c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS node;')
    
    op.create_table('node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('x_position', sa.Integer(), nullable=False),
    sa.Column('y_position', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='node'
    )
    op.create_table('analysis_node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.analysis_jobs_results.job_id'], ),
    sa.ForeignKeyConstraint(['id'], ['node.node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='node'
    )
    op.create_table('automation_node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('automation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automation.automation.id'], ),
    sa.ForeignKeyConstraint(['id'], ['node.node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='node'
    )
    op.create_table('dataset_node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['ontology.dataset.job_id'], ),
    sa.ForeignKeyConstraint(['id'], ['node.node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='node'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_node', schema='node')
    op.drop_table('automation_node', schema='node')
    op.drop_table('analysis_node', schema='node')
    op.drop_table('node', schema='node')
    # ### end Alembic commands ###
