"""empty message

Revision ID: bf9e48508a30
Revises: ec5d2dd0f353
Create Date: 2025-04-11 14:09:20.096297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9e48508a30'
down_revision: Union[str, None] = 'ec5d2dd0f353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eda_jobs_results', sa.Column('dataset_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'integration_jobs_results', ['dataset_id'])
    op.create_foreign_key(None, 'eda_jobs_results', 'integration_jobs_results', ['dataset_id'], ['dataset_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eda_jobs_results', type_='foreignkey')
    op.drop_constraint(None, 'integration_jobs_results', type_='unique')
    op.drop_column('eda_jobs_results', 'dataset_id')
    # ### end Alembic commands ###
