"""project

Revision ID: cc63914dbb03
Revises: 1bd9c7146ba7
Create Date: 2025-06-15 11:31:04.919140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc63914dbb03'
down_revision: Union[str, None] = '1bd9c7146ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS project;')
    
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='project'
    )
    op.create_table('project_analysis',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'analysis_id'),
    schema='project'
    )
    op.create_table('project_automation',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('automation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'automation_id'),
    schema='project'
    )
    op.create_table('project_dataset',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'dataset_id'),
    schema='project'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_dataset', schema='project')
    op.drop_table('project_automation', schema='project')
    op.drop_table('project_analysis', schema='project')
    op.drop_table('project', schema='project')
    # ### end Alembic commands ###
