"""status updates for analysis

Revision ID: e048eb9e6b84
Revises: 284caa5b8bc0
Create Date: 2025-05-12 16:55:40.315104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e048eb9e6b84'
down_revision: Union[str, None] = '284caa5b8bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_status_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='analysis'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_status_messages', schema='analysis')
    # ### end Alembic commands ###
