"""add_new_data_integration_tables

Revision ID: f6b43b05f4aa
Revises: 90e4ee9b3071
Create Date: 2025-07-23 20:29:48.205561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6b43b05f4aa'
down_revision: Union[str, None] = '90e4ee9b3071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_group',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='data_integration'
                    )
    op.create_table('subgroup',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('parent_group_id', sa.UUID(), nullable=False),
                    sa.Column('child_group_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['child_group_id'], [
                        'data_integration.data_source_group.id'], ),
                    sa.ForeignKeyConstraint(['parent_group_id'], [
                        'data_integration.data_source_group.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='data_integration'
                    )
    op.create_table('data_source_in_group',
                    sa.Column('group_id', sa.UUID(), nullable=False),
                    sa.Column('data_source_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['data_source_id'], [
                        'data_integration.data_source.id'], ),
                    sa.ForeignKeyConstraint(
                        ['group_id'], ['data_integration.data_source_group.id'], ),
                    sa.PrimaryKeyConstraint('group_id'),
                    schema='data_integration'
                    )
    op.create_table('file_data_source',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('file_name', sa.String(), nullable=False),
                    sa.Column('file_path', sa.String(), nullable=False),
                    sa.Column('file_type', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['id'], ['data_integration.data_source.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='data_integration'
                    )
    op.drop_table('local_directory_file', schema='data_integration')
    op.drop_table('local_directory_data_source', schema='data_integration')

    # Drop the old constraint first
    op.drop_constraint('data_source_type_check', 'data_source',
                       schema='data_integration', type_='check')

    # Update existing data_source rows from 'local_directory' to 'file' type
    op.execute(
        "UPDATE data_integration.data_source SET type = 'file' WHERE type = 'local_directory'")

    # Create the new constraint
    op.create_check_constraint(
        'data_source_type_check', 'data_source', "type IN ('file')", schema='data_integration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_directory_data_source',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('directory_name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('save_path', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['id'], [
                        'data_integration.data_source.id'], name='local_directory_data_source_id_fkey'),
                    sa.PrimaryKeyConstraint(
                        'id', name='local_directory_data_source_pkey'),
                    schema='data_integration'
                    )
    op.create_table('local_directory_file',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('directory_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('file_name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('file_path', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('file_type', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['directory_id'], [
                        'data_integration.local_directory_data_source.id'], name='local_directory_file_directory_id_fkey'),
                    sa.PrimaryKeyConstraint(
                        'id', name='local_directory_file_pkey'),
                    schema='data_integration'
                    )
    op.drop_table('file_data_source', schema='data_integration')
    op.drop_table('data_source_in_group', schema='data_integration')
    op.drop_table('subgroup', schema='data_integration')
    op.drop_table('data_source_group', schema='data_integration')

    # Drop the new constraint first
    op.drop_constraint('data_source_type_check', 'data_source',
                       schema='data_integration', type_='check')

    # Update existing data_source rows from 'file' back to 'local_directory' type
    op.execute(
        "UPDATE data_integration.data_source SET type = 'local_directory' WHERE type = 'file'")

    # Restore the original constraint on data_source table
    op.create_check_constraint('data_source_type_check', 'data_source',
                               "type IN ('local_directory')", schema='data_integration')
    # ### end Alembic commands ###
