from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe037d23538e'
down_revision: Union[str, None] = 'e93ee5c6fdda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('python_package_name',
                              sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch_node')),
                    schema='entity_graph'
                    )
    op.create_table('edge',
                    sa.Column('from_entity_id', sa.UUID(), nullable=False),
                    sa.Column('to_entity_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint(
                        'from_entity_id', 'to_entity_id', name=op.f('pk_edge')),
                    schema='entity_graph'
                    )
    op.create_table('node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('x_position', sa.Float(), nullable=False),
                    sa.Column('y_position', sa.Float(), nullable=False),
                    sa.Column('node_type', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_node')),
                    schema='entity_graph'
                    )
    op.create_table('leaf_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('entity_id', sa.UUID(), nullable=False),
                    sa.Column('entity_type', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['id'], ['entity_graph.node.id'], name=op.f('fk_leaf_node_id_node')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_leaf_node')),
                    schema='entity_graph'
                    )
    op.create_table('parent_child_relation',
                    sa.Column('child_id', sa.UUID(), nullable=False),
                    sa.Column('parent_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['child_id'], ['entity_graph.node.id'], name=op.f(
                        'fk_parent_child_relation_child_id_node')),
                    sa.ForeignKeyConstraint(['parent_id'], ['entity_graph.node.id'], name=op.f(
                        'fk_parent_child_relation_parent_id_node')),
                    sa.PrimaryKeyConstraint('child_id', 'parent_id',
                                            name=op.f('pk_parent_child_relation')),
                    schema='entity_graph'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_child_relation', schema='entity_graph')
    op.drop_table('leaf_node', schema='entity_graph')
    op.drop_table('node', schema='entity_graph')
    op.drop_table('edge', schema='entity_graph')
    op.drop_table('branch_node', schema='entity_graph')
    # ### end Alembic commands ###
