FROM python:3.13-slim

WORKDIR /app

# Copy the data_structures package first for better caching
COPY data_structures /app/data_structures

# Copy the api project files
COPY main_server/api /app

# Install synesis data structures package from source and the main package
RUN pip install --upgrade pip && \
    pip install -e /app/data_structures && \
    pip install -e .

CMD ["uvicorn", "src.synesis_api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] 