FROM python:3.13-slim

WORKDIR /app

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy the data_structures package first for better caching
COPY data_structures /app/data_structures

COPY schemas /app/schemas

COPY project_server/server /app/server

# Copy the sandbox project files
COPY project_server/sandbox /app

# Install synesis data structures package from source and the main package
RUN pip install --upgrade pip && \
    pip install -e /app/data_structures && \
    pip install -e /app/schemas && \
    pip install -e /app/server && \
    pip install -e .

CMD ["tail", "-f", "/dev/null"]
