"""Add analysis from past analysis model

Revision ID: 0a486f7b6bc6
Revises: 2735a4df59c9
Create Date: 2025-10-22 15:42:16.437716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a486f7b6bc6'
down_revision: Union[str, None] = '2735a4df59c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_from_past_analysis',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_id', sa.UUID(), nullable=False),
                    sa.Column('past_analysis_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.analysis.id'], name=op.f(
                        'fk_analysis_from_past_analysis_analysis_id_analysis')),
                    sa.ForeignKeyConstraint(['past_analysis_id'], ['analysis.analysis.id'], name=op.f(
                        'fk_analysis_from_past_analysis_past_analysis_id_analysis')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_analysis_from_past_analysis')),
                    schema='analysis'
                    )
    op.drop_table('run_specification', schema='runs')
    op.add_column('run', sa.Column(
        'run_name', sa.String(), nullable=False), schema='runs')
    op.add_column('run', sa.Column('plan_and_deliverable_description_for_user',
                  sa.String(), nullable=False), schema='runs')
    op.add_column('run', sa.Column('plan_and_deliverable_description_for_agent',
                  sa.String(), nullable=False), schema='runs')
    op.add_column('run', sa.Column('questions_for_user',
                  sa.String(), nullable=True), schema='runs')
    op.add_column('run', sa.Column('configuration_defaults_description',
                  sa.String(), nullable=True), schema='runs')
    op.drop_constraint(op.f('run_parent_run_id_fkey'), 'run',
                       schema='runs', type_='foreignkey')
    op.drop_column('run', 'parent_run_id', schema='runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('parent_run_id', sa.UUID(),
                  autoincrement=False, nullable=True), schema='runs')
    op.create_foreign_key(op.f('run_parent_run_id_fkey'), 'run', 'run', [
                          'parent_run_id'], ['id'], source_schema='runs', referent_schema='runs')
    op.drop_column('run', 'configuration_defaults_description', schema='runs')
    op.drop_column('run', 'questions_for_user', schema='runs')
    op.drop_column(
        'run', 'plan_and_deliverable_description_for_agent', schema='runs')
    op.drop_column(
        'run', 'plan_and_deliverable_description_for_user', schema='runs')
    op.drop_column('run', 'run_name', schema='runs')
    op.create_table('run_specification',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('run_name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('plan_and_deliverable_description_for_user',
                              sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('plan_and_deliverable_description_for_agent',
                              sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('questions_for_user', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('configuration_defaults_description',
                              sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('run_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'run_specification_run_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('run_specification_pkey')),
                    schema='runs'
                    )
    op.drop_table('analysis_from_past_analysis', schema='analysis')
    # ### end Alembic commands ###
