"""Upgrade analysis

Revision ID: 0bbc9775af9f
Revises: 449f3106dcaf
Create Date: 2025-10-27 00:01:41.913789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bbc9775af9f'
down_revision: Union[str, None] = '449f3106dcaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('script',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('user_id', sa.UUID(), nullable=False),
    # sa.Column('output', sa.String(), nullable=True),
    # sa.Column('error', sa.String(), nullable=True),
    # sa.Column('path', sa.String(), nullable=False),
    # sa.Column('filename', sa.String(), nullable=False),
    # sa.Column('module_path', sa.String(), nullable=True),
    # sa.Column('type', sa.String(), nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_script_user_id_users')),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_script')),
    # schema='code'
    # )
    # op.drop_table('project_entity_group', schema='project')
    op.execute('DROP TABLE IF EXISTS project.project_entity_group CASCADE')
    op.add_column('plot', sa.Column('plot_url', sa.String(),
                  nullable=False), schema='analysis')
    op.drop_column('plot', 'plot_config', schema='analysis')
    # op.drop_constraint(op.f('fk_project_analysis_entity_group_id_project_entity_group'),
    #                    'project_analysis', schema='project', type_='foreignkey')
    op.drop_column('project_analysis', 'entity_group_id', schema='project')
    # op.drop_constraint(op.f('fk_project_data_source_entity_group_id_project_entity_group'),
    #                    'project_data_source', schema='project', type_='foreignkey')
    op.drop_column('project_data_source', 'entity_group_id', schema='project')
    # op.drop_constraint(op.f('fk_project_dataset_entity_group_id_project_entity_group'),
    #                    'project_dataset', schema='project', type_='foreignkey')
    op.drop_column('project_dataset', 'entity_group_id', schema='project')
    # op.drop_constraint(op.f('fk_project_model_entity_entity_group_id_project_entity_group'),
    #                    'project_model_entity', schema='project', type_='foreignkey')
    op.drop_column('project_model_entity', 'entity_group_id', schema='project')
    # op.drop_constraint(op.f('fk_project_pipeline_entity_group_id_project_entity_group'),
    #                    'project_pipeline', schema='project', type_='foreignkey')
    op.drop_column('project_pipeline', 'entity_group_id', schema='project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_pipeline', sa.Column('entity_group_id',
                  sa.UUID(), autoincrement=False, nullable=True), schema='project')
    op.create_foreign_key(op.f('fk_project_pipeline_entity_group_id_project_entity_group'), 'project_pipeline',
                          'project_entity_group', ['entity_group_id'], ['id'], source_schema='project', referent_schema='project')
    op.add_column('project_model_entity', sa.Column('entity_group_id',
                  sa.UUID(), autoincrement=False, nullable=True), schema='project')
    op.create_foreign_key(op.f('fk_project_model_entity_entity_group_id_project_entity_group'), 'project_model_entity',
                          'project_entity_group', ['entity_group_id'], ['id'], source_schema='project', referent_schema='project')
    op.add_column('project_dataset', sa.Column('entity_group_id', sa.UUID(
    ), autoincrement=False, nullable=True), schema='project')
    op.create_foreign_key(op.f('fk_project_dataset_entity_group_id_project_entity_group'), 'project_dataset',
                          'project_entity_group', ['entity_group_id'], ['id'], source_schema='project', referent_schema='project')
    op.add_column('project_data_source', sa.Column('entity_group_id',
                  sa.UUID(), autoincrement=False, nullable=True), schema='project')
    op.create_foreign_key(op.f('fk_project_data_source_entity_group_id_project_entity_group'), 'project_data_source',
                          'project_entity_group', ['entity_group_id'], ['id'], source_schema='project', referent_schema='project')
    op.add_column('project_analysis', sa.Column('entity_group_id',
                  sa.UUID(), autoincrement=False, nullable=True), schema='project')
    op.create_foreign_key(op.f('fk_project_analysis_entity_group_id_project_entity_group'), 'project_analysis',
                          'project_entity_group', ['entity_group_id'], ['id'], source_schema='project', referent_schema='project')
    op.add_column('plot', sa.Column('plot_config', postgresql.JSON(
        astext_type=sa.Text()), autoincrement=False, nullable=False), schema='analysis')
    op.drop_column('plot', 'plot_url', schema='analysis')
    op.create_table('project_entity_group',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('project_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('parent_entity_group_id', sa.UUID(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['parent_entity_group_id'], ['project.project_entity_group.id'], name=op.f(
                        'fk_project_entity_group_parent_entity_group_id_project__39fd')),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_project_entity_group_project_id_project')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_project_entity_group')),
                    schema='project'
                    )

    # ### end Alembic commands ###
