"""Simplify pipeline

Revision ID: 14779194f837
Revises: 31aef8c4ad29
Create Date: 2025-10-19 01:17:43.906752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14779194f837'
down_revision: Union[str, None] = '31aef8c4ad29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_in_pipeline',
                    sa.Column('data_source_id', sa.UUID(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_data_source_in_pipeline_data_source_id_data_source')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_data_source_in_pipeline_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint('data_source_id', 'pipeline_id', name=op.f(
                        'pk_data_source_in_pipeline')),
                    schema='pipeline'
                    )
    op.create_table('dataset_in_pipeline',
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_dataset_in_pipeline_dataset_id_dataset')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_dataset_in_pipeline_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint(
                        'dataset_id', 'pipeline_id', name=op.f('pk_dataset_in_pipeline')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_implementation',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('python_function_name',
                              sa.String(), nullable=False),
                    sa.Column('docstring', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('args', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('args_schema', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('output_variables_schema', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('implementation_script_id',
                              sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_pipeline_implementation_id_pipeline')),
                    sa.ForeignKeyConstraint(['implementation_script_id'], ['code.script.id'], name=op.f(
                        'fk_pipeline_implementation_implementation_script_id_script')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_pipeline_implementation')),
                    schema='pipeline'
                    )
    op.create_table('model_entity_implementation',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('model_id', sa.UUID(), nullable=False),
                    sa.Column('config', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('weights_save_dir', sa.String(), nullable=True),
                    sa.Column('pipeline_id', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['model.model_entity.id'], name=op.f(
                        'fk_model_entity_implementation_id_model_entity')),
                    sa.ForeignKeyConstraint(['model_id'], ['model.model.id'], name=op.f(
                        'fk_model_entity_implementation_model_id_model')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_model_entity_implementation_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_model_entity_implementation')),
                    schema='model'
                    )
    op.drop_table('pipeline_graph_model_entity_node', schema='pipeline')
    op.drop_table('pipeline_graph_edge', schema='pipeline')
    op.drop_table('project_model_entity_being_created', schema='project')
    op.drop_table('object_group_in_pipeline', schema='pipeline')
    op.drop_table('pipeline_on_event_schedule', schema='pipeline')
    op.drop_table('project_pipeline_being_created', schema='project')
    op.drop_table('pipeline_graph_function_node', schema='pipeline')
    op.drop_table('pipeline_graph_dataset_node', schema='pipeline')
    op.drop_table('project_dataset_being_created', schema='project')
    op.drop_table('pipeline_output_object_group_definition', schema='pipeline')
    op.drop_table('pipeline_periodic_schedule', schema='pipeline')
    op.drop_table('pipeline_graph_node', schema='pipeline')
    op.add_column('variable_group', sa.Column('group_schema', postgresql.JSONB(
        astext_type=sa.Text()), nullable=False), schema='data_objects')
    op.alter_column('model_entity', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    schema='model')
    op.drop_constraint(op.f('model_entity_model_id_fkey'),
                       'model_entity', schema='model', type_='foreignkey')
    op.drop_constraint(op.f('model_entity_pipeline_id_fkey'),
                       'model_entity', schema='model', type_='foreignkey')
    op.drop_column('model_entity', 'model_id', schema='model')
    op.drop_column('model_entity', 'config', schema='model')
    op.drop_column('model_entity', 'weights_save_dir', schema='model')
    op.drop_column('model_entity', 'pipeline_id', schema='model')
    op.drop_constraint(op.f('fk_pipeline_implementation_script_id_script'),
                       'pipeline', schema='pipeline', type_='foreignkey')
    op.drop_column('pipeline', 'output_variables_dataclass_name',
                   schema='pipeline')
    op.drop_column('pipeline', 'docstring', schema='pipeline')
    op.drop_column('pipeline', 'args_dataclass_name', schema='pipeline')
    op.drop_column('pipeline', 'output_variables_schema', schema='pipeline')
    op.drop_column('pipeline', 'output_dataclass_name', schema='pipeline')
    op.drop_column('pipeline', 'args_schema', schema='pipeline')
    op.drop_column('pipeline', 'python_function_name', schema='pipeline')
    op.drop_column('pipeline', 'args', schema='pipeline')
    op.drop_column('pipeline', 'input_dataclass_name', schema='pipeline')
    op.drop_column('pipeline', 'implementation_script_id', schema='pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('implementation_script_id', sa.UUID(
    ), autoincrement=False, nullable=False), schema='pipeline')
    op.add_column('pipeline', sa.Column('input_dataclass_name', sa.VARCHAR(
    ), autoincrement=False, nullable=False), schema='pipeline')
    op.add_column('pipeline', sa.Column('args', postgresql.JSONB(
        astext_type=sa.Text()), autoincrement=False, nullable=True), schema='pipeline')
    op.add_column('pipeline', sa.Column('python_function_name', sa.VARCHAR(
    ), autoincrement=False, nullable=False), schema='pipeline')
    op.add_column('pipeline', sa.Column('args_schema', postgresql.JSONB(
        astext_type=sa.Text()), autoincrement=False, nullable=False), schema='pipeline')
    op.add_column('pipeline', sa.Column('output_dataclass_name', sa.VARCHAR(
    ), autoincrement=False, nullable=False), schema='pipeline')
    op.add_column('pipeline', sa.Column('output_variables_schema', postgresql.JSONB(
        astext_type=sa.Text()), autoincrement=False, nullable=False), schema='pipeline')
    op.add_column('pipeline', sa.Column('args_dataclass_name', sa.VARCHAR(
    ), autoincrement=False, nullable=False), schema='pipeline')
    op.add_column('pipeline', sa.Column('docstring', sa.VARCHAR(),
                  autoincrement=False, nullable=False), schema='pipeline')
    op.add_column('pipeline', sa.Column('output_variables_dataclass_name',
                  sa.VARCHAR(), autoincrement=False, nullable=False), schema='pipeline')
    op.create_foreign_key(op.f('fk_pipeline_implementation_script_id_script'), 'pipeline', 'script', [
                          'implementation_script_id'], ['id'], source_schema='pipeline', referent_schema='code')
    op.add_column('model_entity', sa.Column('pipeline_id', sa.UUID(),
                  autoincrement=False, nullable=True), schema='model')
    op.add_column('model_entity', sa.Column('weights_save_dir', sa.VARCHAR(
    ), autoincrement=False, nullable=True), schema='model')
    op.add_column('model_entity', sa.Column('config', postgresql.JSONB(
        astext_type=sa.Text()), autoincrement=False, nullable=False), schema='model')
    op.add_column('model_entity', sa.Column('model_id', sa.UUID(),
                  autoincrement=False, nullable=False), schema='model')
    op.create_foreign_key(op.f('model_entity_pipeline_id_fkey'), 'model_entity', 'pipeline', [
                          'pipeline_id'], ['id'], source_schema='model', referent_schema='pipeline')
    op.create_foreign_key(op.f('model_entity_model_id_fkey'), 'model_entity', 'model', [
                          'model_id'], ['id'], source_schema='model', referent_schema='model')
    op.alter_column('model_entity', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    schema='model')
    op.drop_column('variable_group', 'group_schema', schema='data_objects')
    op.create_table('pipeline_graph_node',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('type', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('pipeline_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.CheckConstraint(
                        "type::text = ANY (ARRAY['dataset'::character varying, 'function'::character varying, 'model_entity'::character varying]::text[])", name='pipeline_graph_node_type_check'),
                    sa.ForeignKeyConstraint(['pipeline_id'], [
                        'pipeline.pipeline.id'], name='pipeline_graph_node_pipeline_id_fkey'),
                    sa.PrimaryKeyConstraint(
                        'id', name='pipeline_graph_node_pkey'),
                    schema='pipeline',
                    postgresql_ignore_search_path=False
                    )
    op.create_table('pipeline_periodic_schedule',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('pipeline_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('start_time', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('schedule_description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('cron_expression', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'pipeline_periodic_schedule_pipeline_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pipeline_periodic_schedule_pkey')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_output_object_group_definition',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('pipeline_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('structure_id', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('output_entity_id_name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'pipeline_output_object_group_definition_pipeline_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pipeline_output_object_group_definition_pkey')),
                    sa.UniqueConstraint('pipeline_id', 'name', name=op.f(
                        'uq_pipeline_output_object_group_definition_pipeline_id'), postgresql_include=[], postgresql_nulls_not_distinct=False),
                    schema='pipeline'
                    )
    op.create_table('project_dataset_being_created',
                    sa.Column('project_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('run_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('x_position', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=False),
                    sa.Column('y_position', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_project_dataset_being_created_project_id_project')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_project_dataset_being_created_run_id_run')),
                    sa.PrimaryKeyConstraint('project_id', 'run_id', name=op.f(
                        'pk_project_dataset_being_created')),
                    schema='project'
                    )
    op.create_table('pipeline_graph_dataset_node',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('dataset_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'pipeline_graph_dataset_node_dataset_id_fkey')),
                    sa.ForeignKeyConstraint(['id'], ['pipeline.pipeline_graph_node.id'], name=op.f(
                        'pipeline_graph_dataset_node_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pipeline_graph_dataset_node_pkey')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_graph_function_node',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('function_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['function_id'], ['function.function.id'], name=op.f(
                        'pipeline_graph_function_node_function_id_fkey')),
                    sa.ForeignKeyConstraint(['id'], ['pipeline.pipeline_graph_node.id'], name=op.f(
                        'pipeline_graph_function_node_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pipeline_graph_function_node_pkey')),
                    schema='pipeline'
                    )
    op.create_table('project_pipeline_being_created',
                    sa.Column('project_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('run_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('x_position', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=False),
                    sa.Column('y_position', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_project_pipeline_being_created_project_id_project')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_project_pipeline_being_created_run_id_run')),
                    sa.PrimaryKeyConstraint('project_id', 'run_id', name=op.f(
                        'pk_project_pipeline_being_created')),
                    schema='project'
                    )
    op.create_table('pipeline_on_event_schedule',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('pipeline_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('event_listener_script_path', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('event_description', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'pipeline_on_event_schedule_pipeline_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pipeline_on_event_schedule_pkey')),
                    schema='pipeline'
                    )
    op.create_table('object_group_in_pipeline',
                    sa.Column('pipeline_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('object_group_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('code_variable_name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['object_group_id'], ['data_objects.object_group.id'], name=op.f(
                        'object_group_in_pipeline_object_group_id_fkey')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'object_group_in_pipeline_pipeline_id_fkey')),
                    sa.PrimaryKeyConstraint('pipeline_id', 'object_group_id', name=op.f(
                        'object_group_in_pipeline_pkey')),
                    schema='pipeline'
                    )
    op.create_table('project_model_entity_being_created',
                    sa.Column('project_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('run_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('x_position', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=False),
                    sa.Column('y_position', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_project_model_entity_being_created_project_id_project')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_project_model_entity_being_created_run_id_run')),
                    sa.PrimaryKeyConstraint('project_id', 'run_id', name=op.f(
                        'pk_project_model_entity_being_created')),
                    schema='project'
                    )
    op.create_table('pipeline_graph_edge',
                    sa.Column('from_node_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('to_node_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['from_node_id'], ['pipeline.pipeline_graph_node.id'], name=op.f(
                        'pipeline_graph_edge_from_node_id_fkey')),
                    sa.ForeignKeyConstraint(['to_node_id'], ['pipeline.pipeline_graph_node.id'], name=op.f(
                        'pipeline_graph_edge_to_node_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'from_node_id', 'to_node_id', name=op.f('pipeline_graph_edge_pkey')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_graph_model_entity_node',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('model_entity_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('function_type', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.CheckConstraint("function_type::text = ANY (ARRAY['training'::character varying, 'inference'::character varying]::text[])", name=op.f(
                        'pipeline_graph_model_entity_node_function_type_check')),
                    sa.ForeignKeyConstraint(['id'], ['pipeline.pipeline_graph_node.id'], name=op.f(
                        'pipeline_graph_model_entity_node_id_fkey')),
                    sa.ForeignKeyConstraint(['model_entity_id'], ['model.model_entity.id'], name=op.f(
                        'pipeline_graph_model_entity_node_model_entity_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pipeline_graph_model_entity_node_pkey')),
                    schema='pipeline'
                    )
    op.drop_table('model_entity_implementation', schema='model')
    op.drop_table('pipeline_implementation', schema='pipeline')
    op.drop_table('dataset_in_pipeline', schema='pipeline')
    op.drop_table('data_source_in_pipeline', schema='pipeline')
    op.drop_table('script', schema='code')
    # ### end Alembic commands ###
