"""Add back project viewport and zoom

Revision ID: 155928c9556a
Revises: 982394692f6e
Create Date: 2025-11-18 05:37:51.003312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155928c9556a'
down_revision: Union[str, None] = '982394692f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_source', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    schema='data_sources')
    op.add_column('project', sa.Column(
        'view_port_x', sa.Float(), nullable=False), schema='project')
    op.add_column('project', sa.Column(
        'view_port_y', sa.Float(), nullable=False), schema='project')
    op.add_column('project', sa.Column('view_port_zoom',
                  sa.Float(), nullable=False), schema='project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'view_port_zoom', schema='project')
    op.drop_column('project', 'view_port_y', schema='project')
    op.drop_column('project', 'view_port_x', schema='project')
    op.alter_column('data_source', 'description',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    schema='data_sources')
    # ### end Alembic commands ###
