"""Separate out function and model from pipeline, add model source

Revision ID: 20c554b5d36b
Revises: 1eb0790d255f
Create Date: 2025-09-19 19:44:47.026933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql
from sqlalchemy import schema

# revision identifiers, used by Alembic.
revision: str = '20c554b5d36b'
down_revision: Union[str, None] = '1eb0790d255f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the new schemas first
    op.execute(schema.CreateSchema('function'))
    op.execute(schema.CreateSchema('model_sources'))
    op.execute(schema.CreateSchema('model'))
    op.create_table('function',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=1536), nullable=False),
                    sa.Column('implementation_script_path',
                              sa.String(), nullable=False),
                    sa.Column('setup_script_path', sa.String(), nullable=True),
                    sa.Column('default_args', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "type IN ('inference', 'training', 'computation', 'tool')"),
                    sa.PrimaryKeyConstraint('id'),
                    schema='function'
                    )
    op.create_table('function_input_structure',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('structure_id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('required', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "structure_id IN ('time_series', 'time_series_aggregation')"),
                    sa.ForeignKeyConstraint(
                        ['function_id'], ['function.function.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='function'
                    )
    op.create_table('function_output_structure',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('structure_id', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.CheckConstraint(
                        "structure_id IN ('time_series', 'time_series_aggregation')"),
                    sa.ForeignKeyConstraint(
                        ['function_id'], ['function.function.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='function'
                    )
    op.create_table('function_output_variable',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('python_type', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['function_id'], ['function.function.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='function'
                    )
    op.create_table('model_source',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('public', sa.Boolean(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=1536), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "type IN ('github', 'pypi', 'gitlab', 'huggingface', 'local')"),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='model_sources'
                    )
    op.create_table('dataset_from_data_source',
                    sa.Column('data_source_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['data_source_id'], [
                        'data_sources.data_source.id'], ),
                    sa.ForeignKeyConstraint(
                        ['dataset_id'], ['data_objects.dataset.id'], ),
                    sa.PrimaryKeyConstraint('data_source_id', 'dataset_id'),
                    schema='data_objects'
                    )
    op.create_table('dataset_from_dataset',
                    sa.Column('source_dataset_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['dataset_id'], ['data_objects.dataset.id'], ),
                    sa.ForeignKeyConstraint(['source_dataset_id'], [
                        'data_objects.dataset.id'], ),
                    sa.PrimaryKeyConstraint('source_dataset_id', 'dataset_id'),
                    schema='data_objects'
                    )
    op.create_table('dataset_from_pipeline',
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['dataset_id'], ['data_objects.dataset.id'], ),
                    sa.ForeignKeyConstraint(
                        ['pipeline_id'], ['pipeline.pipeline.id'], ),
                    sa.PrimaryKeyConstraint('pipeline_id', 'dataset_id'),
                    schema='data_objects'
                    )
    op.create_table('model',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=1536), nullable=False),
                    sa.Column('source_id', sa.UUID(), nullable=False),
                    sa.Column('owner_id', sa.UUID(), nullable=False),
                    sa.Column('public', sa.Boolean(), nullable=False),
                    sa.Column('modality', sa.String(), nullable=False),
                    sa.Column('default_config', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('programming_language_with_version',
                              sa.String(), nullable=False),
                    sa.Column('setup_script_path', sa.String(), nullable=True),
                    sa.Column('task', sa.String(), nullable=False),
                    sa.Column('inference_function_id',
                              sa.UUID(), nullable=False),
                    sa.Column('training_function_id',
                              sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "modality IN ('time_series', 'tabular', 'multimodal', 'image', 'text', 'audio', 'video')"),
                    sa.CheckConstraint(
                        "task IN ('forecasting', 'classification', 'regression', 'clustering', 'anomaly_detection', 'generation', 'segmentation')"),
                    sa.ForeignKeyConstraint(['inference_function_id'], [
                        'function.function.id'], ),
                    sa.ForeignKeyConstraint(['owner_id'], ['auth.users.id'], ),
                    sa.ForeignKeyConstraint(
                        ['source_id'], ['model_sources.model_source.id'], ),
                    sa.ForeignKeyConstraint(['training_function_id'], [
                        'function.function.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='model'
                    )
    op.create_table('pypi_model_source',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('package_name', sa.String(), nullable=False),
                    sa.Column('package_version', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['id'], ['model_sources.model_source.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='model_sources'
                    )
    op.create_table('model_source_context',
                    sa.Column('context_id', sa.UUID(), nullable=False),
                    sa.Column('model_source_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['context_id'], ['orchestrator.chat_context.id'], ),
                    sa.ForeignKeyConstraint(['model_source_id'], [
                        'model_sources.model_source.id'], ),
                    sa.PrimaryKeyConstraint('context_id', 'model_source_id'),
                    schema='orchestrator'
                    )
    op.create_table('pipeline_from_dataset',
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['dataset_id'], ['data_objects.dataset.id'], ),
                    sa.ForeignKeyConstraint(
                        ['pipeline_id'], ['pipeline.pipeline.id'], ),
                    sa.PrimaryKeyConstraint('dataset_id', 'pipeline_id'),
                    schema='pipeline'
                    )
    op.create_table('project_model_source',
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('model_source_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['model_source_id'], [
                        'model_sources.model_source.id'], ),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['project.project.id'], ),
                    sa.PrimaryKeyConstraint('project_id', 'model_source_id'),
                    schema='project'
                    )
    op.create_table('model_entity',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('model_id', sa.UUID(), nullable=False),
                    sa.Column('weights_save_dir', sa.String(), nullable=True),
                    sa.Column('pipeline_id', sa.UUID(), nullable=True),
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('config', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['model_id'], ['model.model.id'], ),
                    sa.ForeignKeyConstraint(
                        ['pipeline_id'], ['pipeline.pipeline.id'], ),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['project.project.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='model'
                    )
    op.create_table('model_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('model_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['node.node.id'], ),
                    sa.ForeignKeyConstraint(
                        ['model_id'], ['model.model.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='node'
                    )
    op.create_table('model_source_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('model_source_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['node.node.id'], ),
                    sa.ForeignKeyConstraint(['model_source_id'], [
                        'model_sources.model_source.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='node'
                    )
    op.create_table('pipeline_from_model',
                    sa.Column('model_id', sa.UUID(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['model_id'], ['model.model.id'], ),
                    sa.ForeignKeyConstraint(
                        ['pipeline_id'], ['pipeline.pipeline.id'], ),
                    sa.PrimaryKeyConstraint('model_id', 'pipeline_id'),
                    schema='pipeline'
                    )
    op.create_table('project_model',
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('model_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['model_id'], ['model.model.id'], ),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['project.project.id'], ),
                    sa.PrimaryKeyConstraint('project_id', 'model_id'),
                    schema='project'
                    )
    op.create_table('model_entity_context',
                    sa.Column('context_id', sa.UUID(), nullable=False),
                    sa.Column('model_entity_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['context_id'], ['orchestrator.chat_context.id'], ),
                    sa.ForeignKeyConstraint(['model_entity_id'], [
                        'model.model_entity.id'], ),
                    sa.PrimaryKeyConstraint('context_id', 'model_entity_id'),
                    schema='orchestrator'
                    )
    op.execute("DROP TABLE IF EXISTS function_output_variable CASCADE")
    op.execute("DROP TABLE IF EXISTS model_task CASCADE")
    op.execute("DROP TABLE IF EXISTS model CASCADE")
    op.execute("DROP TABLE IF EXISTS function_output_structure CASCADE")
    op.execute("DROP TABLE IF EXISTS function CASCADE")
    op.execute("DROP TABLE IF EXISTS function_input_structure CASCADE")
    # op.drop_table('function_output_variable', schema='pipeline')
    # op.drop_table('model_task', schema='pipeline')
    # op.drop_table('model', schema='pipeline')
    # op.drop_table('function_output_structure', schema='pipeline')
    # op.drop_table('function', schema='pipeline')
    # op.drop_table('function_input_structure', schema='pipeline')
    op.drop_constraint(op.f('function_in_pipeline_function_id_fkey'),
                       'function_in_pipeline', schema='pipeline', type_='foreignkey')
    op.create_foreign_key(None, 'function_in_pipeline', 'function', ['function_id'], [
                          'id'], source_schema='pipeline', referent_schema='function')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'function_in_pipeline',
                       schema='pipeline', type_='foreignkey')
    op.create_foreign_key(op.f('function_in_pipeline_function_id_fkey'), 'function_in_pipeline', 'function', [
                          'function_id'], ['id'], source_schema='pipeline', referent_schema='pipeline')
    op.create_table('function_input_structure',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('function_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('structure_id', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('required', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.CheckConstraint("structure_id::text = ANY (ARRAY['time_series'::character varying, 'time_series_aggregation'::character varying]::text[])", name=op.f(
                        'function_input_structure_structure_id_check')),
                    sa.ForeignKeyConstraint(['function_id'], ['pipeline.function.id'], name=op.f(
                        'function_input_structure_function_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'function_input_structure_pkey')),
                    schema='pipeline'
                    )
    op.create_table('function',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=1536), autoincrement=False, nullable=False),
                    sa.Column('implementation_script_path', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('setup_script_path', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('default_config', postgresql.JSONB(
                        astext_type=sa.Text()), autoincrement=False, nullable=True),
                    sa.Column('type', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='function_pkey'),
                    schema='pipeline',
                    postgresql_ignore_search_path=False
                    )
    op.create_table('function_output_structure',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('function_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('structure_id', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.CheckConstraint("structure_id::text = ANY (ARRAY['time_series'::character varying, 'time_series_aggregation'::character varying]::text[])", name=op.f(
                        'function_output_structure_structure_id_check')),
                    sa.ForeignKeyConstraint(['function_id'], ['pipeline.function.id'], name=op.f(
                        'function_output_structure_function_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'function_output_structure_pkey')),
                    schema='pipeline'
                    )
    op.create_table('model',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('owner_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('public', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.Column('modality', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('source', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('programming_language_with_version', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('setup_script_path', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('default_config', postgresql.JSONB(
                        astext_type=sa.Text()), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.CheckConstraint(
                        "modality::text = ANY (ARRAY['time_series'::character varying, 'tabular'::character varying, 'multimodal'::character varying, 'image'::character varying, 'text'::character varying, 'audio'::character varying, 'video'::character varying]::text[])", name='model_modality_check'),
                    sa.CheckConstraint(
                        "source::text = ANY (ARRAY['github'::character varying, 'pypi'::character varying, 'gitlab'::character varying, 'huggingface'::character varying, 'local'::character varying]::text[])", name='model_source_check'),
                    sa.ForeignKeyConstraint(
                        ['owner_id'], ['auth.users.id'], name='model_owner_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='model_pkey'),
                    schema='pipeline',
                    postgresql_ignore_search_path=False
                    )
    op.create_table('model_task',
                    sa.Column('model_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('task', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('inference_function_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('training_function_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.CheckConstraint("task::text = ANY (ARRAY['forecasting'::character varying, 'classification'::character varying, 'regression'::character varying, 'clustering'::character varying, 'anomaly_detection'::character varying, 'generation'::character varying, 'segmentation'::character varying]::text[])", name=op.f(
                        'model_task_task_check')),
                    sa.ForeignKeyConstraint(['inference_function_id'], [
                        'pipeline.function.id'], name=op.f('model_task_inference_function_id_fkey')),
                    sa.ForeignKeyConstraint(
                        ['model_id'], ['pipeline.model.id'], name=op.f('model_task_model_id_fkey')),
                    sa.ForeignKeyConstraint(['training_function_id'], [
                        'pipeline.function.id'], name=op.f('model_task_training_function_id_fkey')),
                    schema='pipeline'
                    )
    op.create_table('function_output_variable',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('function_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('python_type', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['function_id'], ['pipeline.function.id'], name=op.f(
                        'function_output_variable_function_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'function_output_variable_pkey')),
                    schema='pipeline'
                    )
    op.drop_table('model_entity_context', schema='orchestrator')
    op.drop_table('project_model', schema='project')
    op.drop_table('pipeline_from_model', schema='pipeline')
    op.drop_table('model_source_node', schema='node')
    op.drop_table('model_node', schema='node')
    op.drop_table('model_entity', schema='model')
    op.drop_table('project_model_source', schema='project')
    op.drop_table('pipeline_from_dataset', schema='pipeline')
    op.drop_table('model_source_context', schema='orchestrator')
    op.drop_table('pypi_model_source', schema='model_sources')
    op.drop_table('model', schema='model')
    op.drop_table('dataset_from_pipeline', schema='data_objects')
    op.drop_table('dataset_from_dataset', schema='data_objects')
    op.drop_table('dataset_from_data_source', schema='data_objects')
    op.drop_table('model_source', schema='model_sources')
    op.drop_table('function_output_variable', schema='function')
    op.drop_table('function_output_structure', schema='function')
    op.drop_table('function_input_structure', schema='function')
    op.drop_table('function', schema='function')
    # Drop the schemas after all tables have been dropped
    op.execute(schema.DropSchema('function'))
    op.execute(schema.DropSchema('model_sources'))
    op.execute(schema.DropSchema('model'))
    # ### end Alembic commands ###
