"""Rename swe deps to deps

Revision ID: 213f4d0429ed
Revises: 874fa94f6e40
Create Date: 2025-11-21 03:39:15.809305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '213f4d0429ed'
down_revision: Union[str, None] = '874fa94f6e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['kvasir_v1.run.id'], name=op.f('fk_deps_run_id_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deps')),
    schema='kvasir_v1'
    )
    op.drop_table('swe_deps', schema='kvasir_v1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swe_deps',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['kvasir_v1.run.id'], name=op.f('fk_swe_deps_run_id_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_swe_deps')),
    schema='kvasir_v1'
    )
    op.drop_table('deps', schema='kvasir_v1')
    # ### end Alembic commands ###
