"""Switch from raw data fn to chart fn in obj group

Revision ID: 21d5decacb5c
Revises: cfaefc59671b
Create Date: 2025-11-04 22:20:28.405249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d5decacb5c'
down_revision: Union[str, None] = 'cfaefc59671b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_group', sa.Column('chart_script_path', sa.String(), nullable=True), schema='data_objects')
    op.drop_column('object_group', 'raw_data_read_script_path', schema='data_objects')
    op.drop_column('object_group', 'raw_data_read_function_name', schema='data_objects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_group', sa.Column('raw_data_read_function_name', sa.VARCHAR(), autoincrement=False, nullable=True), schema='data_objects')
    op.add_column('object_group', sa.Column('raw_data_read_script_path', sa.VARCHAR(), autoincrement=False, nullable=True), schema='data_objects')
    op.drop_column('object_group', 'chart_script_path', schema='data_objects')
    # ### end Alembic commands ###
