"""Add separate tables for schedules

Revision ID: 2336a232eaa3
Revises: 10bb84b0a015
Create Date: 2025-08-26 20:54:38.081010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2336a232eaa3'
down_revision: Union[str, None] = '10bb84b0a015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_on_event_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('event_listener_script_path', sa.String(), nullable=False),
    sa.Column('event_description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pipeline'
    )
    op.create_table('pipeline_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='pipeline'
    )
    op.drop_column('pipeline', 'schedule', schema='pipeline')
    op.drop_column('pipeline', 'cron_schedule', schema='pipeline')
    op.add_column('pipeline_periodic_schedule', sa.Column('schedule_description', sa.String(), nullable=True), schema='pipeline')
    op.add_column('pipeline_periodic_schedule', sa.Column('cron_expression', sa.String(), nullable=True), schema='pipeline')
    op.drop_column('pipeline_periodic_schedule', 'cron_schedule', schema='pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_periodic_schedule', sa.Column('cron_schedule', sa.VARCHAR(), autoincrement=False, nullable=True), schema='pipeline')
    op.drop_column('pipeline_periodic_schedule', 'cron_expression', schema='pipeline')
    op.drop_column('pipeline_periodic_schedule', 'schedule_description', schema='pipeline')
    op.add_column('pipeline', sa.Column('cron_schedule', sa.VARCHAR(), autoincrement=False, nullable=True), schema='pipeline')
    op.add_column('pipeline', sa.Column('schedule', sa.VARCHAR(), autoincrement=False, nullable=False), schema='pipeline')
    op.drop_table('pipeline_run', schema='pipeline')
    op.drop_table('pipeline_on_event_schedule', schema='pipeline')
    # ### end Alembic commands ###
