"""Make chat message type field obligatory

Revision ID: 254b30ce4bcd
Revises: b4dbdc28e453
Create Date: 2025-10-23 15:30:30.462145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254b30ce4bcd'
down_revision: Union[str, None] = 'b4dbdc28e453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'type',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    schema='orchestrator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'type',
                    existing_type=sa.VARCHAR(),
                    nullable=True,
                    schema='orchestrator')
    # ### end Alembic commands ###
