"""Add analysis object source models

Revision ID: 2700912e8ff1
Revises: 93145d52a6b9
Create Date: 2025-10-21 19:14:02.336976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2700912e8ff1'
down_revision: Union[str, None] = '93145d52a6b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('script',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('user_id', sa.UUID(), nullable=False),
    # sa.Column('output', sa.String(), nullable=True),
    # sa.Column('error', sa.String(), nullable=True),
    # sa.Column('path', sa.String(), nullable=False),
    # sa.Column('filename', sa.String(), nullable=False),
    # sa.Column('module_path', sa.String(), nullable=True),
    # sa.Column('type', sa.String(), nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    # sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_script_user_id_users')),
    # sa.PrimaryKeyConstraint('id', name=op.f('pk_script')),
    # schema='code'
    # )
    op.create_table('data_source_in_analysis',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_object_id', sa.UUID(), nullable=False),
                    sa.Column('data_source_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_object_id'], ['analysis.analysis_object.id'], name=op.f(
                        'fk_data_source_in_analysis_analysis_object_id_analysis_object')),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_data_source_in_analysis_data_source_id_data_source')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_data_source_in_analysis')),
                    schema='analysis'
                    )
    op.create_table('dataset_in_analysis',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_object_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_object_id'], ['analysis.analysis_object.id'], name=op.f(
                        'fk_dataset_in_analysis_analysis_object_id_analysis_object')),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_dataset_in_analysis_dataset_id_dataset')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_dataset_in_analysis')),
                    schema='analysis'
                    )
    op.create_table('model_instantiated_in_analysis',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_object_id', sa.UUID(), nullable=False),
                    sa.Column('model_instantiated_id',
                              sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_object_id'], ['analysis.analysis_object.id'], name=op.f(
                        'fk_model_entity_in_analysis_analysis_object_id_analysis_object')),
                    sa.ForeignKeyConstraint(['model_instantiated_id'], ['model.model_instantiated.id'], name=op.f(
                        'fk_model_entity_in_analysis_model_entity_id_model_entity')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_model_entity_in_analysis')),
                    schema='analysis'
                    )
    op.create_table('analysis_from_run',
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('analysis_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.analysis_object.id'], name=op.f(
                        'fk_analysis_from_run_analysis_id_analysis_object')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_analysis_from_run_run_id_run')),
                    sa.PrimaryKeyConstraint('run_id', 'analysis_id',
                                            name=op.f('pk_analysis_from_run')),
                    schema='runs'
                    )
    op.drop_table('run_summary', schema='runs')
    op.drop_table('analysis_result_data_source', schema='analysis')
    op.drop_table('analysis_result_dataset', schema='analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_result_dataset',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('dataset_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_analysis_result_dataset_analysis_result_id_analysis_result')),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_analysis_result_dataset_dataset_id_dataset')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_analysis_result_dataset')),
                    schema='analysis'
                    )
    op.create_table('analysis_result_data_source',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('data_source_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_analysis_result_data_source_analysis_result_id_analy_cbbf')),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_analysis_result_data_source_data_source_id_data_source')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_analysis_result_data_source')),
                    schema='analysis'
                    )
    op.create_table('run_summary',
                    sa.Column('run_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('summary', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['run_id'], ['runs.run.id'], name=op.f('fk_run_summary_run_id_run')),
                    sa.PrimaryKeyConstraint(
                        'run_id', name=op.f('pk_run_summary')),
                    schema='runs'
                    )
    op.drop_table('analysis_from_run', schema='runs')
    op.drop_table('model_instantiated_in_analysis', schema='analysis')
    op.drop_table('dataset_in_analysis', schema='analysis')
    op.drop_table('data_source_in_analysis', schema='analysis')
    # op.drop_table('script', schema='code')
    # ### end Alembic commands ###
