"""Remove order from fn inp/out

Revision ID: 27f414cf6fdd
Revises: f0016774b7a0
Create Date: 2025-09-12 15:45:52.824371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f414cf6fdd'
down_revision: Union[str, None] = 'f0016774b7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('function_input', 'position', schema='pipeline')
    op.drop_column('function_output', 'position', schema='pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function_output', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False), schema='pipeline')
    op.add_column('function_input', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False), schema='pipeline')
    # ### end Alembic commands ###
