"""Add function definition foreign key

Revision ID: 2fa2300fc4d2
Revises: d7ea92878fd3
Create Date: 2025-09-29 22:33:51.345437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa2300fc4d2'
down_revision: Union[str, None] = 'd7ea92878fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function', sa.Column('definition_id', sa.UUID(), nullable=False), schema='function')
    op.create_foreign_key(None, 'function', 'function_definition', ['definition_id'], ['id'], source_schema='function', referent_schema='function')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'function', schema='function', type_='foreignkey')
    op.drop_column('function', 'definition_id', schema='function')
    # ### end Alembic commands ###
