"""Merge node and project, and model and model source

Revision ID: 31aef8c4ad29
Revises: 61e426a951b8
Create Date: 2025-10-15 18:03:45.099399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31aef8c4ad29'
down_revision: Union[str, None] = '61e426a951b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_dataset_being_created',
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('x_position', sa.Float(), nullable=False),
                    sa.Column('y_position', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_project_dataset_being_created_project_id_project')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_project_dataset_being_created_run_id_run')),
                    sa.PrimaryKeyConstraint('project_id', 'run_id', name=op.f(
                        'pk_project_dataset_being_created')),
                    schema='project'
                    )
    op.create_table('project_model_entity_being_created',
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('x_position', sa.Float(), nullable=False),
                    sa.Column('y_position', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_project_model_entity_being_created_project_id_project')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_project_model_entity_being_created_run_id_run')),
                    sa.PrimaryKeyConstraint('project_id', 'run_id', name=op.f(
                        'pk_project_model_entity_being_created')),
                    schema='project'
                    )
    op.create_table('project_pipeline_being_created',
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('x_position', sa.Float(), nullable=False),
                    sa.Column('y_position', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_project_pipeline_being_created_project_id_project')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_project_pipeline_being_created_run_id_run')),
                    sa.PrimaryKeyConstraint('project_id', 'run_id', name=op.f(
                        'pk_project_pipeline_being_created')),
                    schema='project'
                    )
    op.drop_table('pipeline_node', schema='node')
    op.drop_table('data_source_node', schema='node')
    op.drop_table('analysis_node', schema='node')
    op.drop_table('model_instantiated_node', schema='node')
    op.drop_table('dataset_node', schema='node')
    op.drop_table('node', schema='node')

    # Move model source tables from model_sources schema to model schema
    op.execute('ALTER TABLE model_sources.pypi_model_source SET SCHEMA model')
    op.execute('ALTER TABLE model_sources.model_source SET SCHEMA model')

    # Drop empty schemas
    op.execute('DROP SCHEMA IF EXISTS model_sources')
    op.execute('DROP SCHEMA IF EXISTS node')

    op.add_column('project_analysis', sa.Column(
        'x_position', sa.Float(), nullable=False), schema='project')
    op.add_column('project_analysis', sa.Column(
        'y_position', sa.Float(), nullable=False), schema='project')
    op.add_column('project_analysis', sa.Column(
        'created_at', sa.DateTime(timezone=True), nullable=False), schema='project')
    op.add_column('project_analysis', sa.Column(
        'updated_at', sa.DateTime(timezone=True), nullable=False), schema='project')
    op.add_column('project_data_source', sa.Column(
        'x_position', sa.Float(), nullable=False), schema='project')
    op.add_column('project_data_source', sa.Column(
        'y_position', sa.Float(), nullable=False), schema='project')
    op.add_column('project_data_source', sa.Column(
        'created_at', sa.DateTime(timezone=True), nullable=False), schema='project')
    op.add_column('project_data_source', sa.Column(
        'updated_at', sa.DateTime(timezone=True), nullable=False), schema='project')
    op.add_column('project_dataset', sa.Column(
        'x_position', sa.Float(), nullable=False), schema='project')
    op.add_column('project_dataset', sa.Column(
        'y_position', sa.Float(), nullable=False), schema='project')
    op.add_column('project_dataset', sa.Column('created_at', sa.DateTime(
        timezone=True), nullable=False), schema='project')
    op.add_column('project_dataset', sa.Column('updated_at', sa.DateTime(
        timezone=True), nullable=False), schema='project')
    op.add_column('project_model_entity', sa.Column(
        'x_position', sa.Float(), nullable=False), schema='project')
    op.add_column('project_model_entity', sa.Column(
        'y_position', sa.Float(), nullable=False), schema='project')
    op.add_column('project_model_entity', sa.Column(
        'created_at', sa.DateTime(timezone=True), nullable=False), schema='project')
    op.add_column('project_model_entity', sa.Column(
        'updated_at', sa.DateTime(timezone=True), nullable=False), schema='project')
    op.add_column('project_pipeline', sa.Column(
        'x_position', sa.Float(), nullable=False), schema='project')
    op.add_column('project_pipeline', sa.Column(
        'y_position', sa.Float(), nullable=False), schema='project')
    op.add_column('project_pipeline', sa.Column(
        'created_at', sa.DateTime(timezone=True), nullable=False), schema='project')
    op.add_column('project_pipeline', sa.Column(
        'updated_at', sa.DateTime(timezone=True), nullable=False), schema='project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_pipeline', 'updated_at', schema='project')
    op.drop_column('project_pipeline', 'created_at', schema='project')
    op.drop_column('project_pipeline', 'y_position', schema='project')
    op.drop_column('project_pipeline', 'x_position', schema='project')
    op.drop_column('project_model_entity', 'updated_at', schema='project')
    op.drop_column('project_model_entity', 'created_at', schema='project')
    op.drop_column('project_model_entity', 'y_position', schema='project')
    op.drop_column('project_model_entity', 'x_position', schema='project')
    op.drop_column('project_dataset', 'updated_at', schema='project')
    op.drop_column('project_dataset', 'created_at', schema='project')
    op.drop_column('project_dataset', 'y_position', schema='project')
    op.drop_column('project_dataset', 'x_position', schema='project')
    op.drop_column('project_data_source', 'updated_at', schema='project')
    op.drop_column('project_data_source', 'created_at', schema='project')
    op.drop_column('project_data_source', 'y_position', schema='project')
    op.drop_column('project_data_source', 'x_position', schema='project')
    op.drop_column('project_analysis', 'updated_at', schema='project')
    op.drop_column('project_analysis', 'created_at', schema='project')
    op.drop_column('project_analysis', 'y_position', schema='project')
    op.drop_column('project_analysis', 'x_position', schema='project')

    # Recreate schemas
    op.execute('CREATE SCHEMA IF NOT EXISTS node')
    op.execute('CREATE SCHEMA IF NOT EXISTS model_sources')

    # Move model source tables back to model_sources schema
    op.execute('ALTER TABLE model.model_source SET SCHEMA model_sources')
    op.execute('ALTER TABLE model.pypi_model_source SET SCHEMA model_sources')

    op.create_table('dataset_node',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('dataset_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'dataset_node_dataset_id_fkey')),
                    sa.ForeignKeyConstraint(
                        ['id'], ['node.node.id'], name=op.f('dataset_node_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('dataset_node_pkey')),
                    schema='node'
                    )
    op.create_table('model_instantiated_node',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('model_instantiated_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['id'], ['node.node.id'], name=op.f('model_instantiated_node_id_fkey')),
                    sa.ForeignKeyConstraint(['model_instantiated_id'], ['model.model_instantiated.id'], name=op.f(
                        'model_instantiated_node_model_entity_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('model_instantiated_node_pkey')),
                    schema='node'
                    )
    op.create_table('node',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('project_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('x_position', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=False),
                    sa.Column('y_position', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=False),
                    sa.Column('type', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['project.project.id'], name='node_project_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='node_pkey'),
                    schema='node',
                    postgresql_ignore_search_path=False
                    )
    op.create_table('analysis_node',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('analysis_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.analysis_object.id'], name=op.f(
                        'fk_analysis_node_analysis_id_analysis_object')),
                    sa.ForeignKeyConstraint(
                        ['id'], ['node.node.id'], name=op.f('analysis_node_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('analysis_node_pkey')),
                    schema='node'
                    )
    op.create_table('data_source_node',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('data_source_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'data_source_node_data_source_id_fkey')),
                    sa.ForeignKeyConstraint(
                        ['id'], ['node.node.id'], name=op.f('data_source_node_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('data_source_node_pkey')),
                    schema='node'
                    )
    op.create_table('pipeline_node',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('pipeline_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['id'], ['node.node.id'], name=op.f('pipeline_node_id_fkey')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'pipeline_node_pipeline_id_fkey')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pipeline_node_pkey')),
                    schema='node'
                    )
    op.drop_table('project_pipeline_being_created', schema='project')
    op.drop_table('project_model_entity_being_created', schema='project')
    op.drop_table('project_dataset_being_created', schema='project')
    op.drop_table('script', schema='code')
    # ### end Alembic commands ###
