"""Update model task primary key

Revision ID: 3a54ac0c3d80
Revises: 3c30b8627e5e
Create Date: 2025-09-15 23:16:54.382419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a54ac0c3d80'
down_revision: Union[str, None] = '3c30b8627e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_task', 'id', schema='pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_task', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False), schema='pipeline')
    # ### end Alembic commands ###
