"""Model entity in pipe rename

Revision ID: 4e0240c8c8a4
Revises: e930699e372e
Create Date: 2025-11-02 18:32:44.531998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e0240c8c8a4'
down_revision: Union[str, None] = 'e930699e372e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_entity_supported_in_pipeline',
    sa.Column('model_entity_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_entity_id'], ['model.model_entity.id'], name=op.f('fk_model_entity_supported_in_pipeline_model_entity_id_model_entity')),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f('fk_model_entity_supported_in_pipeline_pipeline_id_pipeline')),
    sa.PrimaryKeyConstraint('model_entity_id', 'pipeline_id', name=op.f('pk_model_entity_supported_in_pipeline')),
    schema='pipeline'
    )
    op.drop_table('model_entity_in_pipeline', schema='pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_entity_in_pipeline',
    sa.Column('model_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pipeline_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['model_entity_id'], ['model.model_entity.id'], name=op.f('fk_model_entity_in_pipeline_model_entity_id_model_entity')),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f('fk_model_entity_in_pipeline_pipeline_id_pipeline')),
    sa.PrimaryKeyConstraint('model_entity_id', 'pipeline_id', name=op.f('pk_model_entity_in_pipeline')),
    schema='pipeline'
    )
    op.drop_table('model_entity_supported_in_pipeline', schema='pipeline')
    # ### end Alembic commands ###
