"""Add args and config schema and defaults

Revision ID: 51a4e6f79a00
Revises: aa1e1d1cd7f6
Create Date: 2025-10-05 00:32:40.031879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51a4e6f79a00'
down_revision: Union[str, None] = 'aa1e1d1cd7f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False), schema='model')
    op.add_column('model', sa.Column('training_args_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False), schema='model')
    op.add_column('model', sa.Column('inference_args_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False), schema='model')
    op.add_column('model', sa.Column('default_training_args', postgresql.JSONB(astext_type=sa.Text()), nullable=False), schema='model')
    op.add_column('model', sa.Column('default_inference_args', postgresql.JSONB(astext_type=sa.Text()), nullable=False), schema='model')
    op.alter_column('model', 'default_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               schema='model')
    op.add_column('model_entity', sa.Column('training_args', postgresql.JSONB(astext_type=sa.Text()), nullable=False), schema='model')
    op.add_column('model_entity', sa.Column('inference_args', postgresql.JSONB(astext_type=sa.Text()), nullable=False), schema='model')
    op.alter_column('model_entity', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               schema='model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_entity', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               schema='model')
    op.drop_column('model_entity', 'inference_args', schema='model')
    op.drop_column('model_entity', 'training_args', schema='model')
    op.alter_column('model', 'default_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               schema='model')
    op.drop_column('model', 'default_inference_args', schema='model')
    op.drop_column('model', 'default_training_args', schema='model')
    op.drop_column('model', 'inference_args_schema', schema='model')
    op.drop_column('model', 'training_args_schema', schema='model')
    op.drop_column('model', 'config_schema', schema='model')
    # ### end Alembic commands ###
