"""Update pipeline tables to store input dataset data objects

Revision ID: 55cd6f5fafba
Revises: 9b35a3c26f26
Create Date: 2025-09-27 01:54:17.430275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55cd6f5fafba'
down_revision: Union[str, None] = '9b35a3c26f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function_in_pipeline_object_group_mapping', sa.Column('from_function_output_object_group_id', sa.UUID(), nullable=True), schema='pipeline')
    op.add_column('function_in_pipeline_object_group_mapping', sa.Column('from_dataset_object_group_id', sa.UUID(), nullable=True), schema='pipeline')
    op.add_column('function_in_pipeline_object_group_mapping', sa.Column('to_function_input_object_group_id', sa.UUID(), nullable=False), schema='pipeline')
    op.drop_constraint(op.f('function_in_pipeline_object_group_mapping_from_function_id_fkey'), 'function_in_pipeline_object_group_mapping', schema='pipeline', type_='foreignkey')
    op.drop_constraint(op.f('function_in_pipeline_object_group_mapping_to_function_id_fkey'), 'function_in_pipeline_object_group_mapping', schema='pipeline', type_='foreignkey')
    op.drop_constraint(op.f('function_in_pipeline_object_g_from_function_output_object__fkey'), 'function_in_pipeline_object_group_mapping', schema='pipeline', type_='foreignkey')
    op.drop_constraint(op.f('function_in_pipeline_object_g_to_function_input_object_gro_fkey'), 'function_in_pipeline_object_group_mapping', schema='pipeline', type_='foreignkey')
    op.create_foreign_key(None, 'function_in_pipeline_object_group_mapping', 'function_output_object_group_desc', ['from_function_output_object_group_id'], ['id'], source_schema='pipeline', referent_schema='function')
    op.create_foreign_key(None, 'function_in_pipeline_object_group_mapping', 'object_group', ['from_dataset_object_group_id'], ['id'], source_schema='pipeline', referent_schema='data_objects')
    op.create_foreign_key(None, 'function_in_pipeline_object_group_mapping', 'function_input_object_group_desc', ['to_function_input_object_group_id'], ['id'], source_schema='pipeline', referent_schema='function')
    op.drop_column('function_in_pipeline_object_group_mapping', 'from_function_output_object_group', schema='pipeline')
    op.drop_column('function_in_pipeline_object_group_mapping', 'to_function_input_object_group', schema='pipeline')
    op.drop_column('function_in_pipeline_object_group_mapping', 'from_function_id', schema='pipeline')
    op.drop_column('function_in_pipeline_object_group_mapping', 'to_function_id', schema='pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function_in_pipeline_object_group_mapping', sa.Column('to_function_id', sa.UUID(), autoincrement=False, nullable=False), schema='pipeline')
    op.add_column('function_in_pipeline_object_group_mapping', sa.Column('from_function_id', sa.UUID(), autoincrement=False, nullable=True), schema='pipeline')
    op.add_column('function_in_pipeline_object_group_mapping', sa.Column('to_function_input_object_group', sa.UUID(), autoincrement=False, nullable=False), schema='pipeline')
    op.add_column('function_in_pipeline_object_group_mapping', sa.Column('from_function_output_object_group', sa.UUID(), autoincrement=False, nullable=True), schema='pipeline')
    op.drop_constraint(None, 'function_in_pipeline_object_group_mapping', schema='pipeline', type_='foreignkey')
    op.drop_constraint(None, 'function_in_pipeline_object_group_mapping', schema='pipeline', type_='foreignkey')
    op.drop_constraint(None, 'function_in_pipeline_object_group_mapping', schema='pipeline', type_='foreignkey')
    op.create_foreign_key(op.f('function_in_pipeline_object_g_to_function_input_object_gro_fkey'), 'function_in_pipeline_object_group_mapping', 'function_input_object_group_desc', ['to_function_input_object_group'], ['id'], source_schema='pipeline', referent_schema='function')
    op.create_foreign_key(op.f('function_in_pipeline_object_g_from_function_output_object__fkey'), 'function_in_pipeline_object_group_mapping', 'function_output_object_group_desc', ['from_function_output_object_group'], ['id'], source_schema='pipeline', referent_schema='function')
    op.create_foreign_key(op.f('function_in_pipeline_object_group_mapping_to_function_id_fkey'), 'function_in_pipeline_object_group_mapping', 'function', ['to_function_id'], ['id'], source_schema='pipeline', referent_schema='function')
    op.create_foreign_key(op.f('function_in_pipeline_object_group_mapping_from_function_id_fkey'), 'function_in_pipeline_object_group_mapping', 'function', ['from_function_id'], ['id'], source_schema='pipeline', referent_schema='function')
    op.drop_column('function_in_pipeline_object_group_mapping', 'to_function_input_object_group_id', schema='pipeline')
    op.drop_column('function_in_pipeline_object_group_mapping', 'from_dataset_object_group_id', schema='pipeline')
    op.drop_column('function_in_pipeline_object_group_mapping', 'from_function_output_object_group_id', schema='pipeline')
    # ### end Alembic commands ###
