"""Add name and desc to model entity

Revision ID: 65bc8549ed15
Revises: 05eb7a3b0a35
Create Date: 2025-09-23 15:25:47.680692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65bc8549ed15'
down_revision: Union[str, None] = '05eb7a3b0a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
