"""Add separate module for visualization

Revision ID: 6fda224b2243
Revises: a1b2c3d4e5f6
Create Date: 2025-11-06 17:42:52.506387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fda224b2243'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS visualization")

    op.create_table('echart',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('chart_script_path',
                              sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_echart')),
                    schema='visualization'
                    )
    op.create_table('image',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('image_url', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_image')),
                    schema='visualization'
                    )
    op.create_table('table',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('table_path', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_table')),
                    schema='visualization'
                    )
    op.create_table('result_echart',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
                    sa.Column('echart_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_result_echart_analysis_result_id_analysis_result')),
                    sa.ForeignKeyConstraint(['echart_id'], ['visualization.echart.id'], name=op.f(
                        'fk_result_echart_echart_id_echart')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_result_echart')),
                    schema='analysis'
                    )
    op.drop_table('result_chart', schema='analysis')
    op.add_column('result_image', sa.Column(
        'image_id', sa.UUID(), nullable=False), schema='analysis')
    op.create_foreign_key(op.f('fk_result_image_image_id_image'), 'result_image', 'image', [
                          'image_id'], ['id'], source_schema='analysis', referent_schema='visualization')
    op.drop_column('result_image', 'image_url', schema='analysis')
    op.add_column('result_table', sa.Column(
        'table_id', sa.UUID(), nullable=False), schema='analysis')
    op.create_foreign_key(op.f('fk_result_table_table_id_table'), 'result_table', 'table', [
                          'table_id'], ['id'], source_schema='analysis', referent_schema='visualization')
    op.drop_column('result_table', 'table_path', schema='analysis')
    op.add_column('object_group', sa.Column(
        'echart_id', sa.UUID(), nullable=True), schema='data_objects')
    op.create_foreign_key(op.f('fk_object_group_echart_id_echart'), 'object_group', 'echart', [
                          'echart_id'], ['id'], source_schema='data_objects', referent_schema='visualization')
    op.drop_column('object_group', 'chart_script_path', schema='data_objects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_group', sa.Column('chart_script_path', sa.VARCHAR(
    ), autoincrement=False, nullable=True), schema='data_objects')
    op.drop_constraint(op.f('fk_object_group_echart_id_echart'),
                       'object_group', schema='data_objects', type_='foreignkey')
    op.drop_column('object_group', 'echart_id', schema='data_objects')
    op.add_column('result_table', sa.Column('table_path', sa.VARCHAR(),
                  autoincrement=False, nullable=True), schema='analysis')
    op.drop_constraint(op.f('fk_result_table_table_id_table'),
                       'result_table', schema='analysis', type_='foreignkey')
    op.drop_column('result_table', 'table_id', schema='analysis')
    op.add_column('result_image', sa.Column('image_url', sa.VARCHAR(),
                  autoincrement=False, nullable=False), schema='analysis')
    op.drop_constraint(op.f('fk_result_image_image_id_image'),
                       'result_image', schema='analysis', type_='foreignkey')
    op.drop_column('result_image', 'image_id', schema='analysis')
    op.create_table('result_chart',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('chart_script_path', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_result_chart_analysis_result_id_analysis_result')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_result_chart')),
                    schema='analysis'
                    )
    op.drop_table('result_echart', schema='analysis')
    op.drop_table('table', schema='visualization')
    op.drop_table('image', schema='visualization')
    op.drop_table('echart', schema='visualization')
    op.execute("DROP SCHEMA IF EXISTS visualization CASCADE")
    # ### end Alembic commands ###
