"""Simplify message model

Revision ID: 73d7a29fa1bd
Revises: d46587c3f64e
Create Date: 2025-11-19 01:47:49.573518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73d7a29fa1bd'
down_revision: Union[str, None] = 'd46587c3f64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['kvasir_v1.run.id'], name=op.f('fk_message_run_id_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message')),
    schema='kvasir_v1'
    )
    op.drop_table('user_message', schema='kvasir_v1')
    op.drop_table('run_message', schema='kvasir_v1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_message',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['kvasir_v1.run.id'], name=op.f('fk_run_message_run_id_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_message')),
    schema='kvasir_v1'
    )
    op.create_table('user_message',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['kvasir_v1.run.id'], name=op.f('fk_user_message_run_id_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_message')),
    schema='kvasir_v1'
    )
    op.drop_table('message', schema='kvasir_v1')
    # ### end Alembic commands ###
