"""Delete redundant entity graph tables

Revision ID: 840661951c79
Revises: 40fad3625239
Create Date: 2025-11-03 03:52:39.066641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '840661951c79'
down_revision: Union[str, None] = '40fad3625239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_from_pipeline', schema='entity_graph')
    op.drop_table('analysis_from_past_analysis', schema='entity_graph')
    op.drop_table('data_source_from_pipeline', schema='entity_graph')
    op.add_column('data_source_in_analysis', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), schema='entity_graph')
    op.add_column('data_source_in_analysis', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False), schema='entity_graph')
    op.add_column('dataset_from_data_source', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), schema='entity_graph')
    op.add_column('dataset_from_data_source', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False), schema='entity_graph')
    op.add_column('dataset_in_analysis', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), schema='entity_graph')
    op.add_column('dataset_in_analysis', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False), schema='entity_graph')
    op.add_column('model_entity_in_analysis', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), schema='entity_graph')
    op.add_column('model_entity_in_analysis', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False), schema='entity_graph')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_entity_in_analysis', 'updated_at', schema='entity_graph')
    op.drop_column('model_entity_in_analysis', 'created_at', schema='entity_graph')
    op.drop_column('dataset_in_analysis', 'updated_at', schema='entity_graph')
    op.drop_column('dataset_in_analysis', 'created_at', schema='entity_graph')
    op.drop_column('dataset_from_data_source', 'updated_at', schema='entity_graph')
    op.drop_column('dataset_from_data_source', 'created_at', schema='entity_graph')
    op.drop_column('data_source_in_analysis', 'updated_at', schema='entity_graph')
    op.drop_column('data_source_in_analysis', 'created_at', schema='entity_graph')
    op.create_table('data_source_from_pipeline',
    sa.Column('data_source_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pipeline_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f('fk_data_source_from_pipeline_data_source_id_data_source')),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f('fk_data_source_from_pipeline_pipeline_id_pipeline')),
    sa.PrimaryKeyConstraint('data_source_id', 'pipeline_id', name=op.f('pk_data_source_from_pipeline')),
    schema='entity_graph'
    )
    op.create_table('analysis_from_past_analysis',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('analysis_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('past_analysis_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.analysis.id'], name=op.f('fk_analysis_from_past_analysis_analysis_id_analysis')),
    sa.ForeignKeyConstraint(['past_analysis_id'], ['analysis.analysis.id'], name=op.f('fk_analysis_from_past_analysis_past_analysis_id_analysis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_from_past_analysis')),
    schema='entity_graph'
    )
    op.create_table('dataset_from_pipeline',
    sa.Column('pipeline_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f('fk_dataset_from_pipeline_dataset_id_dataset')),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f('fk_dataset_from_pipeline_pipeline_id_pipeline')),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline.pipeline_run.id'], name=op.f('fk_dataset_from_pipeline_pipeline_run_id_pipeline_run')),
    sa.PrimaryKeyConstraint('pipeline_id', 'dataset_id', name=op.f('pk_dataset_from_pipeline')),
    schema='entity_graph'
    )
    # ### end Alembic commands ###
