"""Add python class name field to model

Revision ID: 84e91eabd621
Revises: eb80ca434f86
Create Date: 2025-10-02 17:46:48.527576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e91eabd621'
down_revision: Union[str, None] = 'eb80ca434f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('python_class_name', sa.String(), nullable=False), schema='model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'python_class_name', schema='model')
    # ### end Alembic commands ###
