"""plot urls

Revision ID: 8dd53662563e
Revises: 0a486f7b6bc6
Create Date: 2025-10-25 20:20:02.634827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dd53662563e'
down_revision: Union[str, None] = '0a486f7b6bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('plot_url', sa.String(), nullable=False), schema='analysis')
    op.drop_column('plot', 'plot_config', schema='analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('plot_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False), schema='analysis')
    op.drop_column('plot', 'plot_url', schema='analysis')
    # ### end Alembic commands ###
