"""Simplify models, remove data structure defs

Revision ID: 9108c99dd4db
Revises: 5231f630b92f
Create Date: 2025-10-31 01:51:08.740306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9108c99dd4db'
down_revision: Union[str, None] = '5231f630b92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_data_source',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('file_name', sa.String(), nullable=False),
                    sa.Column('file_path', sa.String(), nullable=False),
                    sa.Column('file_type', sa.String(), nullable=False),
                    sa.Column('file_size_bytes',
                              sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_file_data_source_id_data_source')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_file_data_source')),
                    schema='data_sources'
                    )
    op.create_table('object_group_from_data_source',
                    sa.Column('data_source_id', sa.UUID(), nullable=False),
                    sa.Column('object_group_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_object_group_from_data_source_data_source_id_data_source')),
                    sa.ForeignKeyConstraint(['object_group_id'], ['data_objects.object_group.id'], name=op.f(
                        'fk_object_group_from_data_source_object_group_id_object_group')),
                    sa.PrimaryKeyConstraint('data_source_id', 'object_group_id', name=op.f(
                        'pk_object_group_from_data_source')),
                    schema='data_objects'
                    )
    op.create_table('object_group_from_pipeline',
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('object_group_id', sa.UUID(), nullable=False),
                    sa.Column('pipeline_run_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['object_group_id'], ['data_objects.object_group.id'], name=op.f(
                        'fk_object_group_from_pipeline_object_group_id_object_group')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_object_group_from_pipeline_pipeline_id_pipeline')),
                    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline.pipeline_run.id'], name=op.f(
                        'fk_object_group_from_pipeline_pipeline_run_id_pipeline_run')),
                    # sa.PrimaryKeyConstraint('pipeline_id', 'object_group_id', 'pipeline_run_id', name=op.f(
                    #     'pk_object_group_from_pipeline')),
                    schema='data_objects'
                    )
    op.create_table('time_series_group',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('total_timestamps',
                              sa.Integer(), nullable=False),
                    sa.Column('number_of_series',
                              sa.Integer(), nullable=False),
                    sa.Column('sampling_frequency',
                              sa.String(), nullable=True),
                    sa.Column('timezone', sa.String(), nullable=True),
                    sa.Column('features_schema', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('earliest_timestamp', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('latest_timestamp', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['data_objects.object_group.id'], name=op.f(
                        'fk_time_series_group_id_object_group')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_time_series_group')),
                    schema='data_objects'
                    )
    op.drop_table('key_value_file_data_source', schema='data_sources')
    op.drop_table('function_output_object_group_definition', schema='function')
    op.drop_table('tabular_file_data_source', schema='data_sources')
    op.drop_table('time_series_object_group', schema='data_objects')
    op.drop_table(
        'model_function_output_object_group_definition', schema='model')
    op.drop_table('feature_in_group', schema='data_objects')
    op.drop_table('time_series_aggregation_object_group',
                  schema='data_objects')
    op.drop_table('aggregation_object', schema='data_objects')
    op.drop_table('function_input_object_group_definition', schema='function')
    op.drop_table('variable_group', schema='data_objects')
    op.drop_table('dataset_from_pipeline', schema='data_objects')
    op.drop_table('data_source_analysis', schema='data_sources')
    op.drop_table('time_series_aggregation_input', schema='data_objects')
    op.drop_table('time_series_aggregation', schema='data_objects')
    op.drop_table('feature', schema='data_objects')
    op.drop_table('model_function_input_object_group_definition',
                  schema='model')
    op.drop_column('data_object', 'structure_type', schema='data_objects')
    op.add_column('object_group', sa.Column(
        'modality', sa.String(), nullable=False), schema='data_objects')
    op.drop_column('object_group', 'save_path', schema='data_objects')
    op.drop_column('object_group', 'structure_type', schema='data_objects')
    op.add_column('time_series', sa.Column('features_schema', postgresql.JSONB(
        astext_type=sa.Text()), nullable=False), schema='data_objects')
    op.add_column('time_series', sa.Column('created_at', sa.DateTime(
        timezone=True), nullable=False), schema='data_objects')
    op.add_column('time_series', sa.Column('updated_at', sa.DateTime(
        timezone=True), nullable=False), schema='data_objects')
    op.add_column('data_source', sa.Column('additional_variables', postgresql.JSONB(
        astext_type=sa.Text()), nullable=True), schema='data_sources')
    op.add_column('pipeline_implementation', sa.Column('default_args', postgresql.JSONB(
        astext_type=sa.Text()), nullable=False), schema='pipeline')
    op.drop_column('pipeline_implementation', 'args', schema='pipeline')
    op.add_column('pipeline_run', sa.Column('args', postgresql.JSONB(
        astext_type=sa.Text()), nullable=True), schema='pipeline')
    op.add_column('pipeline_run', sa.Column('output_variables', postgresql.JSONB(
        astext_type=sa.Text()), nullable=True), schema='pipeline')
    op.add_column('project', sa.Column('python_package_name',
                  sa.String(), nullable=False), schema='project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'python_package_name', schema='project')
    op.drop_column('pipeline_run', 'output_variables', schema='pipeline')
    op.drop_column('pipeline_run', 'args', schema='pipeline')
    op.add_column('pipeline_implementation', sa.Column('args', postgresql.JSONB(
        astext_type=sa.Text()), autoincrement=False, nullable=True), schema='pipeline')
    op.drop_column('pipeline_implementation',
                   'default_args', schema='pipeline')
    op.drop_column('data_source', 'additional_variables',
                   schema='data_sources')
    op.drop_column('time_series', 'updated_at', schema='data_objects')
    op.drop_column('time_series', 'created_at', schema='data_objects')
    op.drop_column('time_series', 'features_schema', schema='data_objects')
    op.add_column('object_group', sa.Column('structure_type', sa.VARCHAR(
    ), autoincrement=False, nullable=False), schema='data_objects')
    op.add_column('object_group', sa.Column('save_path', sa.VARCHAR(
    ), autoincrement=False, nullable=False), schema='data_objects')
    op.drop_column('object_group', 'modality', schema='data_objects')
    op.add_column('data_object', sa.Column('structure_type', sa.VARCHAR(
    ), autoincrement=False, nullable=False), schema='data_objects')
    op.create_table('model_function_input_object_group_definition',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('function_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('structure_id', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('required', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.CheckConstraint("structure_id::text = ANY (ARRAY['time_series'::character varying, 'time_series_aggregation'::character varying]::text[])", name=op.f(
                        'model_function_input_object_group_definition_structure_id_check')),
                    sa.ForeignKeyConstraint(['function_id'], ['model.model_function.id'], name=op.f(
                        'fk_model_function_input_object_group_definition_functio_94e3')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_model_function_input_object_group_definition')),
                    schema='model'
                    )
    op.create_table('feature',
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('unit', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('type', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('subtype', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('scale', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('name', name='pk_feature'),
                    schema='data_objects',
                    postgresql_ignore_search_path=False
                    )
    op.create_table('time_series_aggregation',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('is_multi_series_computation', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['data_objects.data_object.id'],
                                            name='fk_time_series_aggregation_id_data_object'),
                    sa.PrimaryKeyConstraint(
                        'id', name='pk_time_series_aggregation'),
                    schema='data_objects',
                    postgresql_ignore_search_path=False
                    )
    op.create_table('time_series_aggregation_input',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('time_series_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('aggregation_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('input_feature_name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('start_timestamp', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('end_timestamp', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.CheckConstraint('start_timestamp < end_timestamp',
                                       name=op.f('time_series_aggregation_input_check')),
                    sa.ForeignKeyConstraint(['aggregation_id'], ['data_objects.time_series_aggregation.id'], name=op.f(
                        'fk_time_series_aggregation_input_aggregation_id_time_se_fcba')),
                    sa.ForeignKeyConstraint(['id'], ['data_objects.data_object.id'], name=op.f(
                        'fk_time_series_aggregation_input_id_data_object')),
                    sa.ForeignKeyConstraint(['time_series_id'], ['data_objects.time_series.id'], name=op.f(
                        'fk_time_series_aggregation_input_time_series_id_time_series')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_time_series_aggregation_input')),
                    schema='data_objects'
                    )
    op.create_table('data_source_analysis',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('data_source_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('content_description', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('quality_description', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('eda_summary', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('cautions', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_data_source_analysis_data_source_id_data_source')),
                    sa.ForeignKeyConstraint(['id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_data_source_analysis_id_data_source')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_data_source_analysis')),
                    schema='data_sources'
                    )
    op.create_table('dataset_from_pipeline',
                    sa.Column('pipeline_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('dataset_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_dataset_from_pipeline_dataset_id_dataset')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_dataset_from_pipeline_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint(
                        'pipeline_id', 'dataset_id', name=op.f('pk_dataset_from_pipeline')),
                    schema='data_objects'
                    )
    op.create_table('variable_group',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('dataset_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('save_path', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('group_schema', postgresql.JSONB(
                        astext_type=sa.Text()), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_variable_group_dataset_id_dataset')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_variable_group')),
                    schema='data_objects'
                    )
    op.create_table('function_input_object_group_definition',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('function_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('structure_id', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('required', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.CheckConstraint("structure_id::text = ANY (ARRAY['time_series'::character varying, 'time_series_aggregation'::character varying]::text[])", name=op.f(
                        'function_input_object_group_definition_structure_id_check')),
                    sa.ForeignKeyConstraint(['function_id'], ['function.function.id'], name=op.f(
                        'fk_function_input_object_group_definition_function_id_function')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_function_input_object_group_definition')),
                    sa.UniqueConstraint('function_id', 'name', name=op.f(
                        'uq_function_input_object_group_definition_function_id'), postgresql_include=[], postgresql_nulls_not_distinct=False),
                    schema='function'
                    )
    op.create_table('aggregation_object',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_aggregation_object_analysis_result_id_analysis_result')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_aggregation_object')),
                    schema='data_objects'
                    )
    op.create_table('time_series_aggregation_object_group',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('time_series_aggregation_outputs_df_schema',
                              sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('time_series_aggregation_outputs_df_head',
                              sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('time_series_aggregation_inputs_df_schema',
                              sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('time_series_aggregation_inputs_df_head',
                              sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('entity_metadata_df_schema', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('entity_metadata_df_head', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('feature_information_df_schema', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('feature_information_df_head', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['data_objects.object_group.id'], name=op.f(
                        'fk_time_series_aggregation_object_group_id_object_group')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_time_series_aggregation_object_group')),
                    schema='data_objects'
                    )
    op.create_table('feature_in_group',
                    sa.Column('group_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('feature_name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('source', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('category_id', sa.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.CheckConstraint("source::text = ANY (ARRAY['data'::character varying, 'metadata'::character varying]::text[])", name=op.f(
                        'feature_in_group_source_check')),
                    sa.ForeignKeyConstraint(['feature_name'], ['data_objects.feature.name'], name=op.f(
                        'fk_feature_in_group_feature_name_feature')),
                    sa.ForeignKeyConstraint(['group_id'], ['data_objects.object_group.id'], name=op.f(
                        'fk_feature_in_group_group_id_object_group')),
                    sa.PrimaryKeyConstraint(
                        'group_id', 'feature_name', name=op.f('pk_feature_in_group')),
                    schema='data_objects'
                    )
    op.create_table('model_function_output_object_group_definition',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('function_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('structure_id', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.CheckConstraint("structure_id::text = ANY (ARRAY['time_series'::character varying, 'time_series_aggregation'::character varying]::text[])", name=op.f(
                        'model_function_output_object_group_definitio_structure_id_check')),
                    sa.ForeignKeyConstraint(['function_id'], ['model.model_function.id'], name=op.f(
                        'fk_model_function_output_object_group_definition_functi_ca67')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_model_function_output_object_group_definition')),
                    schema='model'
                    )
    op.create_table('time_series_object_group',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('time_series_df_schema', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('time_series_df_head', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('entity_metadata_df_schema', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('entity_metadata_df_head', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('feature_information_df_schema', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('feature_information_df_head', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['data_objects.object_group.id'], name=op.f(
                        'fk_time_series_object_group_id_object_group')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_time_series_object_group')),
                    schema='data_objects'
                    )
    op.create_table('tabular_file_data_source',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('file_name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('file_path', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('file_type', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('file_size_bytes', sa.BIGINT(),
                              autoincrement=False, nullable=False),
                    sa.Column('num_rows', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('num_columns', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('content_preview', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('json_schema', postgresql.JSONB(
                        astext_type=sa.Text()), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_tabular_file_data_source_id_data_source')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_tabular_file_data_source')),
                    schema='data_sources'
                    )
    op.create_table('function_output_object_group_definition',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('output_entity_id_name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('function_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('structure_id', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.CheckConstraint("structure_id::text = ANY (ARRAY['time_series'::character varying, 'time_series_aggregation'::character varying]::text[])", name=op.f(
                        'function_output_object_group_definition_structure_id_check')),
                    sa.ForeignKeyConstraint(['function_id'], ['function.function.id'], name=op.f(
                        'fk_function_output_object_group_definition_function_id_function')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_function_output_object_group_definition')),
                    sa.UniqueConstraint('function_id', 'name', name=op.f(
                        'uq_function_output_object_group_definition_function_id'), postgresql_include=[], postgresql_nulls_not_distinct=False),
                    schema='function'
                    )
    op.create_table('key_value_file_data_source',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('file_name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('file_path', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('file_type', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('file_size_bytes', sa.BIGINT(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_key_value_file_data_source_id_data_source')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_key_value_file_data_source')),
                    schema='data_sources'
                    )
    op.drop_table('time_series_group', schema='data_objects')
    op.drop_table('object_group_from_pipeline', schema='data_objects')
    op.drop_table('object_group_from_data_source', schema='data_objects')
    op.drop_table('file_data_source', schema='data_sources')
    # ### end Alembic commands ###
