"""Add fields storing input / output info to function

Revision ID: 968919c78730
Revises: 55cd6f5fafba
Create Date: 2025-09-27 17:55:11.893745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '968919c78730'
down_revision: Union[str, None] = '55cd6f5fafba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function', sa.Column('args_dataclass_name', sa.String(), nullable=False), schema='function')
    op.add_column('function', sa.Column('input_dataclass_name', sa.String(), nullable=False), schema='function')
    op.add_column('function', sa.Column('output_dataclass_name', sa.String(), nullable=False), schema='function')
    op.add_column('function', sa.Column('output_variables_dataclass_name', sa.String(), nullable=False), schema='function')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('function', 'output_variables_dataclass_name', schema='function')
    op.drop_column('function', 'output_dataclass_name', schema='function')
    op.drop_column('function', 'input_dataclass_name', schema='function')
    op.drop_column('function', 'args_dataclass_name', schema='function')
    # ### end Alembic commands ###
