"""Add user id to pipeline

Revision ID: 9889b0047c04
Revises: cecefa0f2f78
Create Date: 2025-08-20 16:08:50.436416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9889b0047c04'
down_revision: Union[str, None] = 'cecefa0f2f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('user_id', sa.UUID(), nullable=False), schema='pipeline')
    op.create_foreign_key(None, 'pipeline', 'users', ['user_id'], ['id'], source_schema='pipeline', referent_schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline', schema='pipeline', type_='foreignkey')
    op.drop_column('pipeline', 'user_id', schema='pipeline')
    # ### end Alembic commands ###
