"""Add code models

Revision ID: 989ea0336b4a
Revises: 50ac0b3f75e6
Create Date: 2025-10-14 17:07:49.282131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '989ea0336b4a'
down_revision: Union[str, None] = '50ac0b3f75e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS code')
    op.create_table('script',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('output', sa.String(), nullable=True),
                    sa.Column('error', sa.String(), nullable=True),
                    sa.Column('path', sa.String(), nullable=False),
                    sa.Column('filename', sa.String(), nullable=False),
                    sa.Column('module_path', sa.String(), nullable=True),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['auth.users.id'], name=op.f('fk_script_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_script')),
                    schema='code'
                    )
    op.drop_table('run_code_message', schema='runs')
    op.add_column('function', sa.Column('implementation_script_id',
                  sa.UUID(), nullable=False), schema='function')
    op.add_column('function', sa.Column('setup_script_id',
                  sa.UUID(), nullable=True), schema='function')
    op.create_foreign_key(op.f('fk_function_implementation_script_id_script'), 'function', 'script', [
                          'implementation_script_id'], ['id'], source_schema='function', referent_schema='code')
    op.create_foreign_key(op.f('fk_function_setup_script_id_script'), 'function', 'script', [
                          'setup_script_id'], ['id'], source_schema='function', referent_schema='code')
    op.drop_column('function', 'setup_script_path', schema='function')
    op.drop_column('function', 'module_path', schema='function')
    op.drop_column('function', 'implementation_script_path', schema='function')
    op.drop_column('function', 'filename', schema='function')
    op.add_column('model', sa.Column('implementation_script_id',
                  sa.UUID(), nullable=False), schema='model')
    op.add_column('model', sa.Column('setup_script_id',
                  sa.UUID(), nullable=True), schema='model')
    op.create_foreign_key(op.f('fk_model_implementation_script_id_script'), 'model', 'script', [
                          'implementation_script_id'], ['id'], source_schema='model', referent_schema='code')
    op.create_foreign_key(op.f('fk_model_setup_script_id_script'), 'model', 'script', [
                          'setup_script_id'], ['id'], source_schema='model', referent_schema='code')
    op.drop_column('model', 'implementation_script_path', schema='model')
    op.drop_column('model', 'filename', schema='model')
    op.drop_column('model', 'setup_script_path', schema='model')
    op.drop_column(
        'model', 'programming_language_with_version', schema='model')
    op.drop_column('model', 'module_path', schema='model')
    op.add_column('pipeline', sa.Column('implementation_script_id',
                  sa.UUID(), nullable=False), schema='pipeline')
    op.create_foreign_key(op.f('fk_pipeline_implementation_script_id_script'), 'pipeline', 'script', [
                          'implementation_script_id'], ['id'], source_schema='pipeline', referent_schema='code')
    op.drop_column('pipeline', 'implementation_script_path', schema='pipeline')
    op.drop_column('pipeline', 'module_path', schema='pipeline')
    op.drop_column('pipeline', 'filename', schema='pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('filename', sa.VARCHAR(),
                  autoincrement=False, nullable=False), schema='pipeline')
    op.add_column('pipeline', sa.Column('module_path', sa.VARCHAR(),
                  autoincrement=False, nullable=False), schema='pipeline')
    op.add_column('pipeline', sa.Column('implementation_script_path', sa.VARCHAR(
    ), autoincrement=False, nullable=False), schema='pipeline')
    op.drop_constraint(op.f('fk_pipeline_implementation_script_id_script'),
                       'pipeline', schema='pipeline', type_='foreignkey')
    op.drop_column('pipeline', 'implementation_script_id', schema='pipeline')
    op.add_column('model', sa.Column('module_path', sa.VARCHAR(),
                  autoincrement=False, nullable=False), schema='model')
    op.add_column('model', sa.Column('programming_language_with_version',
                  sa.VARCHAR(), autoincrement=False, nullable=False), schema='model')
    op.add_column('model', sa.Column('setup_script_path', sa.VARCHAR(),
                  autoincrement=False, nullable=True), schema='model')
    op.add_column('model', sa.Column('filename', sa.VARCHAR(),
                  autoincrement=False, nullable=False), schema='model')
    op.add_column('model', sa.Column('implementation_script_path', sa.VARCHAR(
    ), autoincrement=False, nullable=False), schema='model')
    op.drop_constraint(op.f('fk_model_setup_script_id_script'),
                       'model', schema='model', type_='foreignkey')
    op.drop_constraint(op.f('fk_model_implementation_script_id_script'),
                       'model', schema='model', type_='foreignkey')
    op.drop_column('model', 'setup_script_id', schema='model')
    op.drop_column('model', 'implementation_script_id', schema='model')
    op.add_column('function', sa.Column('filename', sa.VARCHAR(),
                  autoincrement=False, nullable=False), schema='function')
    op.add_column('function', sa.Column('implementation_script_path', sa.VARCHAR(
    ), autoincrement=False, nullable=False), schema='function')
    op.add_column('function', sa.Column('module_path', sa.VARCHAR(),
                  autoincrement=False, nullable=False), schema='function')
    op.add_column('function', sa.Column('setup_script_path', sa.VARCHAR(
    ), autoincrement=False, nullable=True), schema='function')
    op.drop_constraint(op.f('fk_function_setup_script_id_script'),
                       'function', schema='function', type_='foreignkey')
    op.drop_constraint(op.f('fk_function_implementation_script_id_script'),
                       'function', schema='function', type_='foreignkey')
    op.drop_column('function', 'setup_script_id', schema='function')
    op.drop_column('function', 'implementation_script_id', schema='function')
    op.create_table('run_code_message',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('code', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('output', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('error', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('filename', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('run_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_run_code_message_run_id_run')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_run_code_message')),
                    schema='runs'
                    )
    op.drop_table('script', schema='code')
    # ### end Alembic commands ###
