"""Add created updated at to pipeline sources

Revision ID: 9ca5afd2a9ea
Revises: f1d8952c5bd1
Create Date: 2025-09-23 17:18:49.226684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca5afd2a9ea'
down_revision: Union[str, None] = 'f1d8952c5bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_from_dataset', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), schema='pipeline')
    op.add_column('pipeline_from_dataset', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False), schema='pipeline')
    op.add_column('pipeline_from_model_entity', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), schema='pipeline')
    op.add_column('pipeline_from_model_entity', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False), schema='pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_from_model_entity', 'updated_at', schema='pipeline')
    op.drop_column('pipeline_from_model_entity', 'created_at', schema='pipeline')
    op.drop_column('pipeline_from_dataset', 'updated_at', schema='pipeline')
    op.drop_column('pipeline_from_dataset', 'created_at', schema='pipeline')
    # ### end Alembic commands ###
