"""tabular modality

Revision ID: a220fe0ba734
Revises: c0e092a825d5
Create Date: 2025-11-16 00:50:59.442016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a220fe0ba734'
down_revision: Union[str, None] = 'c0e092a825d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabular_group',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number_of_entities', sa.Integer(), nullable=False),
    sa.Column('number_of_features', sa.Integer(), nullable=False),
    sa.Column('features_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['data_objects.object_group.id'], name=op.f('fk_tabular_group_id_object_group')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tabular_group')),
    schema='data_objects'
    )
    op.create_table('tabular',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('features_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['data_objects.data_object.id'], name=op.f('fk_tabular_id_data_object')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tabular')),
    schema='data_objects'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabular', schema='data_objects')
    op.drop_table('tabular_group', schema='data_objects')
    # ### end Alembic commands ###
