"""Add structure-specific object group fields

Revision ID: aa1e1d1cd7f6
Revises: 52e4b0e0d25f
Create Date: 2025-10-03 22:13:49.222432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1e1d1cd7f6'
down_revision: Union[str, None] = '52e4b0e0d25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_series_aggregation_object_group',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_series_aggregation_outputs_df_schema', sa.String(), nullable=False),
    sa.Column('time_series_aggregation_outputs_df_head', sa.String(), nullable=False),
    sa.Column('time_series_aggregation_inputs_df_schema', sa.String(), nullable=False),
    sa.Column('time_series_aggregation_inputs_df_head', sa.String(), nullable=False),
    sa.Column('entity_metadata_df_schema', sa.String(), nullable=False),
    sa.Column('entity_metadata_df_head', sa.String(), nullable=False),
    sa.Column('feature_information_df_schema', sa.String(), nullable=False),
    sa.Column('feature_information_df_head', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['data_objects.object_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='data_objects'
    )
    op.create_table('time_series_object_group',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_series_df_schema', sa.String(), nullable=False),
    sa.Column('time_series_df_head', sa.String(), nullable=False),
    sa.Column('entity_metadata_df_schema', sa.String(), nullable=False),
    sa.Column('entity_metadata_df_head', sa.String(), nullable=False),
    sa.Column('feature_information_df_schema', sa.String(), nullable=False),
    sa.Column('feature_information_df_head', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['data_objects.object_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='data_objects'
    )
    op.add_column('data_object', sa.Column('structure_type', sa.String(), nullable=False), schema='data_objects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_object', 'structure_type', schema='data_objects')
    op.drop_table('time_series_object_group', schema='data_objects')
    op.drop_table('time_series_aggregation_object_group', schema='data_objects')
    # ### end Alembic commands ###
