"""Add ERD positions to pipeline runs

Revision ID: af81f05bfa0c
Revises: 840661951c79
Create Date: 2025-11-03 22:40:01.535394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af81f05bfa0c'
down_revision: Union[str, None] = '840661951c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_pipeline', sa.Column('run_box_x_position', sa.Float(), nullable=False), schema='project')
    op.add_column('project_pipeline', sa.Column('run_box_y_position', sa.Float(), nullable=False), schema='project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_pipeline', 'run_box_y_position', schema='project')
    op.drop_column('project_pipeline', 'run_box_x_position', schema='project')
    # ### end Alembic commands ###
