"""Remove ERD positions from pipeline runs

Revision ID: b3c631731929
Revises: af81f05bfa0c
Create Date: 2025-11-04 04:12:47.578315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c631731929'
down_revision: Union[str, None] = 'af81f05bfa0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_pipeline', 'run_box_x_position', schema='project')
    op.drop_column('project_pipeline', 'run_box_y_position', schema='project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_pipeline', sa.Column('run_box_y_position', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False), schema='project')
    op.add_column('project_pipeline', sa.Column('run_box_x_position', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False), schema='project')
    # ### end Alembic commands ###
