"""Add tool call type to chat message

Revision ID: b4dbdc28e453
Revises: 0a486f7b6bc6
Create Date: 2025-10-23 15:26:33.189936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4dbdc28e453'
down_revision: Union[str, None] = '0a486f7b6bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column(
        'type', sa.String(), nullable=True), schema='orchestrator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'type', schema='orchestrator')
    # ### end Alembic commands ###
