"""Add analysis tables

Revision ID: ba0204bd5c59
Revises: 20ef15ec2473
Create Date: 2025-10-12 16:25:55.045193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba0204bd5c59'
down_revision: Union[str, None] = '20ef15ec2473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebook',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_notebook')),
                    schema='analysis'
                    )
    op.create_table('notebook_section',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('notebook_id', sa.UUID(), nullable=False),
                    sa.Column('section_name', sa.String(), nullable=False),
                    sa.Column('section_description',
                              sa.String(), nullable=True),
                    sa.Column('next_type', sa.String(), nullable=True),
                    sa.Column('next_id', sa.UUID(), nullable=True),
                    sa.Column('parent_section_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['notebook_id'], ['analysis.notebook.id'], name=op.f(
                        'fk_notebook_section_notebook_id_notebook')),
                    sa.ForeignKeyConstraint(['parent_section_id'], ['analysis.notebook_section.id'], name=op.f(
                        'fk_notebook_section_parent_section_id_notebook_section')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_notebook_section')),
                    schema='analysis'
                    )
    op.create_table('analysis_object',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('report_generated',
                              sa.Boolean(), nullable=False),
                    sa.Column('notebook_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_analysis_object_project_id_project')),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f(
                        'fk_analysis_object_user_id_users')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_analysis_object')),
                    schema='analysis'
                    )
    op.create_table('analysis_result',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis', sa.String(), nullable=False),
                    sa.Column('python_code', sa.String(), nullable=True),
                    sa.Column('output_variable', sa.String(), nullable=True),
                    sa.Column('input_variable', sa.String(), nullable=True),
                    sa.Column('section_id', sa.UUID(), nullable=True),
                    sa.Column('next_type', sa.String(), nullable=True),
                    sa.Column('next_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['section_id'], ['analysis.notebook_section.id'], name=op.f(
                        'fk_analysis_result_section_id_notebook_section')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_analysis_result')),
                    schema='analysis'
                    )
    op.create_table('analysis_result_data_source',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
                    sa.Column('data_source_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_analysis_result_data_source_analysis_result_id_analysis_result')),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_analysis_result_data_source_data_source_id_data_source')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_analysis_result_data_source')),
                    schema='analysis'
                    )
    op.create_table('analysis_result_dataset',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_analysis_result_dataset_analysis_result_id_analysis_result')),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_analysis_result_dataset_dataset_id_dataset')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_analysis_result_dataset')),
                    schema='analysis'
                    )
    op.create_table('plot',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
                    sa.Column('plot_config', sa.JSON(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_plot_analysis_result_id_analysis_result')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_plot')),
                    schema='analysis'
                    )
    op.create_table('table',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
                    sa.Column('table_config', sa.JSON(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_table_analysis_result_id_analysis_result')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_table')),
                    schema='analysis'
                    )
    op.create_table('aggregation_object',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_aggregation_object_analysis_result_id_analysis_result')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_aggregation_object')),
                    schema='data_objects'
                    )
    op.create_table('analysis_status_message',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('message', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_analysis_status_message_analysis_result_id_analysis_result')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_analysis_status_message_run_id_run')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_analysis_status_message')),
                    schema='analysis'
                    )
    op.drop_table('analysis_jobs_datasets', schema='analysis')
    op.drop_table('analysis_jobs_pipelines', schema='analysis')
    op.drop_table('analysis_status_messages', schema='analysis')

    # USe raw sql to drop cascade since other tables depend on these
    # op.drop_table('analysis_jobs_results', schema='analysis')
    op.execute('DROP TABLE IF EXISTS analysis.analysis_jobs_results CASCADE')

    op.drop_constraint(op.f('user_api_keys_key_key'),
                       'user_api_keys', schema='auth', type_='unique')
    op.create_unique_constraint(
        op.f('uq_user_api_keys_key'), 'user_api_keys', ['key'], schema='auth')
    op.drop_constraint(op.f('users_email_key'), 'users',
                       schema='auth', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', [
                                'email'], schema='auth')
    op.drop_constraint(op.f('function_definition_name_key'),
                       'function_definition', schema='function', type_='unique')
    op.create_unique_constraint(op.f(
        'uq_function_definition_name'), 'function_definition', ['name'], schema='function')
    op.drop_constraint(op.f('function_input_object_group_definition_function_id_name_key'),
                       'function_input_object_group_definition', schema='function', type_='unique')
    op.create_unique_constraint(op.f('uq_function_input_object_group_definition_function_id'),
                                'function_input_object_group_definition', ['function_id', 'name'], schema='function')
    op.drop_constraint(op.f('function_output_object_group_definition_function_id_name_key'),
                       'function_output_object_group_definition', schema='function', type_='unique')
    op.create_unique_constraint(op.f('uq_function_output_object_group_definition_function_id'),
                                'function_output_object_group_definition', ['function_id', 'name'], schema='function')
    # op.drop_constraint(op.f('analysis_node_analysis_id_fkey'),
    #                    'analysis_node', schema='node', type_='foreignkey')
    op.create_foreign_key(op.f('fk_analysis_node_analysis_id_analysis_object'), 'analysis_node', 'analysis_object', [
                          'analysis_id'], ['id'], source_schema='node', referent_schema='analysis')
    # op.drop_constraint(op.f('analysis_context_analysis_id_fkey'),
    #                    'analysis_context', schema='orchestrator', type_='foreignkey')
    op.create_foreign_key(op.f('fk_analysis_context_analysis_id_analysis_object'), 'analysis_context', 'analysis_object', [
                          'analysis_id'], ['id'], source_schema='orchestrator', referent_schema='analysis')
    op.drop_constraint(op.f('pipeline_output_object_group_definition_pipeline_id_name_key'),
                       'pipeline_output_object_group_definition', schema='pipeline', type_='unique')
    op.create_unique_constraint(op.f('uq_pipeline_output_object_group_definition_pipeline_id'),
                                'pipeline_output_object_group_definition', ['pipeline_id', 'name'], schema='pipeline')
    # op.drop_constraint(op.f('project_analysis_analysis_id_fkey'),
    #                    'project_analysis', schema='project', type_='foreignkey')
    op.create_foreign_key(op.f('fk_project_analysis_analysis_id_analysis_object'), 'project_analysis', 'analysis_object', [
                          'analysis_id'], ['id'], source_schema='project', referent_schema='analysis')
    # op.drop_constraint(op.f('analysis_in_run_analysis_id_fkey'),
    #                    'analysis_in_run', schema='runs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_analysis_in_run_analysis_id_analysis_object'), 'analysis_in_run', 'analysis_object', [
                          'analysis_id'], ['id'], source_schema='runs', referent_schema='analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_analysis_in_run_analysis_id_analysis_object'),
                       'analysis_in_run', schema='runs', type_='foreignkey')
    op.create_foreign_key(op.f('analysis_in_run_analysis_id_fkey'), 'analysis_in_run', 'analysis_jobs_results', [
                          'analysis_id'], ['job_id'], source_schema='runs', referent_schema='analysis')
    op.drop_constraint(op.f('fk_project_analysis_analysis_id_analysis_object'),
                       'project_analysis', schema='project', type_='foreignkey')
    op.create_foreign_key(op.f('project_analysis_analysis_id_fkey'), 'project_analysis', 'analysis_jobs_results', [
                          'analysis_id'], ['job_id'], source_schema='project', referent_schema='analysis')
    op.drop_constraint(op.f('uq_pipeline_output_object_group_definition_pipeline_id'),
                       'pipeline_output_object_group_definition', schema='pipeline', type_='unique')
    op.create_unique_constraint(op.f('pipeline_output_object_group_definition_pipeline_id_name_key'), 'pipeline_output_object_group_definition', [
                                'pipeline_id', 'name'], schema='pipeline', postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('fk_analysis_context_analysis_id_analysis_object'),
                       'analysis_context', schema='orchestrator', type_='foreignkey')
    op.create_foreign_key(op.f('analysis_context_analysis_id_fkey'), 'analysis_context', 'analysis_jobs_results', [
                          'analysis_id'], ['job_id'], source_schema='orchestrator', referent_schema='analysis')
    op.drop_constraint(op.f('fk_analysis_node_analysis_id_analysis_object'),
                       'analysis_node', schema='node', type_='foreignkey')
    op.create_foreign_key(op.f('analysis_node_analysis_id_fkey'), 'analysis_node', 'analysis_jobs_results', [
                          'analysis_id'], ['job_id'], source_schema='node', referent_schema='analysis')
    op.drop_constraint(op.f('uq_function_output_object_group_definition_function_id'),
                       'function_output_object_group_definition', schema='function', type_='unique')
    op.create_unique_constraint(op.f('function_output_object_group_definition_function_id_name_key'), 'function_output_object_group_definition', [
                                'function_id', 'name'], schema='function', postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_function_input_object_group_definition_function_id'),
                       'function_input_object_group_definition', schema='function', type_='unique')
    op.create_unique_constraint(op.f('function_input_object_group_definition_function_id_name_key'), 'function_input_object_group_definition', [
                                'function_id', 'name'], schema='function', postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_function_definition_name'),
                       'function_definition', schema='function', type_='unique')
    op.create_unique_constraint(op.f('function_definition_name_key'), 'function_definition', [
                                'name'], schema='function', postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_users_email'), 'users',
                       schema='auth', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', [
                                'email'], schema='auth', postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_user_api_keys_key'),
                       'user_api_keys', schema='auth', type_='unique')
    op.create_unique_constraint(op.f('user_api_keys_key_key'), 'user_api_keys', [
                                'key'], schema='auth', postgresql_nulls_not_distinct=False)
    op.create_table('analysis_jobs_results',
                    sa.Column('job_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('number_of_datasets', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('analysis_plan', postgresql.JSONB(
                        astext_type=sa.Text()), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.Column('pdf_created', sa.BOOLEAN(),
                              autoincrement=False, nullable=False),
                    sa.Column('pdf_s3_path', sa.VARCHAR(),
                              autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('number_of_pipelines', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['runs.run.id'], name=op.f(
                        'analysis_jobs_results_job_id_fkey')),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f(
                        'analysis_jobs_results_user_id_fkey')),
                    sa.PrimaryKeyConstraint('job_id', name=op.f(
                        'analysis_jobs_results_pkey')),
                    schema='analysis'
                    )
    op.create_table('analysis_status_messages',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('job_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('type', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('message', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(
                        timezone=True), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['runs.run.id'], name=op.f(
                        'analysis_status_messages_job_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'analysis_status_messages_pkey')),
                    schema='analysis'
                    )
    op.create_table('analysis_jobs_pipelines',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('job_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('pipeline_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['job_id'], ['runs.run.id'], name=op.f(
                        'analysis_jobs_pipelines_job_id_fkey')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'analysis_jobs_pipelines_pipeline_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'analysis_jobs_pipelines_pkey')),
                    schema='analysis'
                    )
    op.create_table('analysis_jobs_datasets',
                    sa.Column('id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('job_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.Column('dataset_id', sa.UUID(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'analysis_jobs_datasets_dataset_id_fkey')),
                    sa.ForeignKeyConstraint(['job_id'], ['runs.run.id'], name=op.f(
                        'analysis_jobs_datasets_job_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'analysis_jobs_datasets_pkey')),
                    schema='analysis'
                    )
    op.drop_table('analysis_status_message', schema='analysis')
    op.drop_table('aggregation_object', schema='data_objects')
    op.drop_table('table', schema='analysis')
    op.drop_table('plot', schema='analysis')
    op.drop_table('analysis_result_dataset', schema='analysis')
    op.drop_table('analysis_result_data_source', schema='analysis')
    op.drop_table('analysis_result', schema='analysis')
    op.drop_table('analysis_object', schema='analysis')
    op.drop_table('notebook_section', schema='analysis')
    op.drop_table('notebook', schema='analysis')
    # ### end Alembic commands ###
