"""Remove args and cfg from fn in pipe (keep it in the pipe input instead)

Revision ID: c1d716cb8ae6
Revises: 2fa2300fc4d2
Create Date: 2025-09-30 02:45:04.115592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1d716cb8ae6'
down_revision: Union[str, None] = '2fa2300fc4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('function_in_pipeline', 'args_dict', schema='pipeline')
    op.drop_column('function_in_pipeline', 'model_config_dict', schema='pipeline')
    op.add_column('pipeline', sa.Column('args_dict', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='pipeline')
    op.add_column('pipeline', sa.Column('args_dataclass_name', sa.String(), nullable=False), schema='pipeline')
    op.add_column('pipeline', sa.Column('input_dataclass_name', sa.String(), nullable=False), schema='pipeline')
    op.add_column('pipeline', sa.Column('output_dataclass_name', sa.String(), nullable=False), schema='pipeline')
    op.add_column('pipeline', sa.Column('output_variables_dataclass_name', sa.String(), nullable=False), schema='pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline', 'output_variables_dataclass_name', schema='pipeline')
    op.drop_column('pipeline', 'output_dataclass_name', schema='pipeline')
    op.drop_column('pipeline', 'input_dataclass_name', schema='pipeline')
    op.drop_column('pipeline', 'args_dataclass_name', schema='pipeline')
    op.drop_column('pipeline', 'args_dict', schema='pipeline')
    op.add_column('function_in_pipeline', sa.Column('model_config_dict', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='pipeline')
    op.add_column('function_in_pipeline', sa.Column('args_dict', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='pipeline')
    # ### end Alembic commands ###
