"""aggregation object

Revision ID: c2f4d500eda2
Revises: 62464f95f74f
Create Date: 2025-10-03 18:57:54.784239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f4d500eda2'
down_revision: Union[str, None] = '62464f95f74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregation_object',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analysis_result_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_results.id'], name=op.f('fk_aggregation_object_analysis_result_id_analysis_results')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aggregation_object')),
    schema='data_objects'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aggregation_object', schema='data_objects')
    # ### end Alembic commands ###
