"""Add additional variables fields to dataset and object group

Revision ID: c8db6c4022c9
Revises: b487c4e5c483
Create Date: 2025-10-31 19:17:08.469149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8db6c4022c9'
down_revision: Union[str, None] = 'b487c4e5c483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('additional_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='data_objects')
    op.add_column('object_group', sa.Column('additional_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='data_objects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_group', 'additional_variables', schema='data_objects')
    op.drop_column('dataset', 'additional_variables', schema='data_objects')
    # ### end Alembic commands ###
