"""fresh start

Revision ID: cc2be69ae54f
Revises: 
Create Date: 2025-10-16 19:57:33.721859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'cc2be69ae54f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("Create schema if not exists analysis")
    op.execute("Create schema if not exists auth")
    op.execute("Create schema if not exists data_objects")
    op.execute("Create schema if not exists function")
    op.execute("Create schema if not exists orchestrator")
    op.execute("Create schema if not exists model")
    op.execute("Create schema if not exists model_sources")
    op.execute("Create schema if not exists pipeline")
    op.execute("Create schema if not exists project")
    op.execute("Create schema if not exists data_sources")
    op.execute("Create schema if not exists node")
    op.execute("Create schema if not exists plots")
    op.execute("Create schema if not exists runs")
    op.execute("Create schema if not exists tables")

    op.create_table('notebook',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_notebook')),
                    schema='analysis'
                    )
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('disabled', sa.Boolean(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
                    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
                    schema='auth'
                    )
    op.create_table('feature',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('unit', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('subtype', sa.String(), nullable=False),
                    sa.Column('scale', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('name', name=op.f('pk_feature')),
                    schema='data_objects'
                    )
    op.create_table('function_definition',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('args_dataclass_name',
                              sa.String(), nullable=False),
                    sa.Column('input_dataclass_name',
                              sa.String(), nullable=False),
                    sa.Column('output_dataclass_name',
                              sa.String(), nullable=False),
                    sa.Column('output_variables_dataclass_name',
                              sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "type IN ('inference', 'training', 'computation', 'tool')"),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_function_definition')),
                    sa.UniqueConstraint('name', name=op.f(
                        'uq_function_definition_name')),
                    schema='function'
                    )
    op.create_table('model_definition',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('modality', sa.String(), nullable=False),
                    sa.Column('task', sa.String(), nullable=False),
                    sa.Column('public', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "modality IN ('time_series', 'tabular', 'multimodal', 'image', 'text', 'audio', 'video')"),
                    sa.CheckConstraint(
                        "task IN ('forecasting', 'classification', 'regression', 'clustering', 'anomaly_detection', 'generation', 'segmentation')"),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_model_definition')),
                    schema='model'
                    )
    op.create_table('model_function',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('docstring', sa.String(), nullable=False),
                    sa.Column('args_schema', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('output_variables_schema', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('default_args', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_model_function')),
                    schema='model'
                    )
    op.create_table('chat_context',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_chat_context')),
                    schema='orchestrator'
                    )
    op.create_table('notebook_section',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('notebook_id', sa.UUID(), nullable=False),
                    sa.Column('section_name', sa.String(), nullable=False),
                    sa.Column('section_description',
                              sa.String(), nullable=True),
                    sa.Column('next_type', sa.String(), nullable=True),
                    sa.Column('next_id', sa.UUID(), nullable=True),
                    sa.Column('parent_section_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['notebook_id'], ['analysis.notebook.id'], name=op.f(
                        'fk_notebook_section_notebook_id_notebook')),
                    sa.ForeignKeyConstraint(['parent_section_id'], ['analysis.notebook_section.id'], name=op.f(
                        'fk_notebook_section_parent_section_id_notebook_section')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_notebook_section')),
                    schema='analysis'
                    )
    op.create_table('user_api_keys',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('key', sa.String(), nullable=False),
                    sa.Column('expires_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f(
                        'fk_user_api_keys_user_id_users')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_user_api_keys')),
                    sa.UniqueConstraint(
                        'key', name=op.f('uq_user_api_keys_key')),
                    schema='auth'
                    )
    op.create_table('dataset',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['auth.users.id'], name=op.f('fk_dataset_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset')),
                    schema='data_objects'
                    )
    op.create_table('data_source',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint("type IN ('file')"),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f(
                        'fk_data_source_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_source')),
                    schema='data_sources'
                    )
    op.create_table('function',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('definition_id', sa.UUID(), nullable=False),
                    sa.Column('version', sa.Integer(), nullable=False),
                    sa.Column('args_schema', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('output_variables_schema', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('newest_update_description',
                              sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('docstring', sa.String(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=1536), nullable=False),
                    sa.Column('filename', sa.String(), nullable=False),
                    sa.Column('python_function_name',
                              sa.String(), nullable=False),
                    sa.Column('implementation_script_path',
                              sa.String(), nullable=False),
                    sa.Column('module_path', sa.String(), nullable=False),
                    sa.Column('setup_script_path', sa.String(), nullable=True),
                    sa.Column('default_args', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['definition_id'], ['function.function_definition.id'], name=op.f(
                        'fk_function_definition_id_function_definition')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_function')),
                    schema='function'
                    )
    op.create_table('model_function_input_object_group_definition',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('structure_id', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('required', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "structure_id IN ('time_series', 'time_series_aggregation')"),
                    sa.ForeignKeyConstraint(['function_id'], ['model.model_function.id'], name=op.f(
                        'fk_model_function_input_object_group_definition_function_id_model_function')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_model_function_input_object_group_definition')),
                    schema='model'
                    )
    op.create_table('model_function_output_object_group_definition',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('structure_id', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "structure_id IN ('time_series', 'time_series_aggregation')"),
                    sa.ForeignKeyConstraint(['function_id'], ['model.model_function.id'], name=op.f(
                        'fk_model_function_output_object_group_definition_function_id_model_function')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_model_function_output_object_group_definition')),
                    schema='model'
                    )
    op.create_table('model_source',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('public', sa.Boolean(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=1536), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "type IN ('github', 'pypi', 'gitlab', 'huggingface', 'local')"),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f(
                        'fk_model_source_user_id_users')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_model_source')),
                    schema='model_sources'
                    )
    op.create_table('pipeline',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('python_function_name',
                              sa.String(), nullable=False),
                    sa.Column('filename', sa.String(), nullable=False),
                    sa.Column('module_path', sa.String(), nullable=False),
                    sa.Column('docstring', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('args', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('args_schema', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('output_variables_schema', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('args_dataclass_name',
                              sa.String(), nullable=False),
                    sa.Column('input_dataclass_name',
                              sa.String(), nullable=False),
                    sa.Column('output_dataclass_name',
                              sa.String(), nullable=False),
                    sa.Column('output_variables_dataclass_name',
                              sa.String(), nullable=False),
                    sa.Column('implementation_script_path',
                              sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['auth.users.id'], name=op.f('fk_pipeline_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline')),
                    schema='pipeline'
                    )
    op.create_table('project',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['auth.users.id'], name=op.f('fk_project_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_project')),
                    schema='project'
                    )
    op.create_table('analysis_object',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('report_generated',
                              sa.Boolean(), nullable=False),
                    sa.Column('notebook_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_analysis_object_project_id_project')),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f(
                        'fk_analysis_object_user_id_users')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_analysis_object')),
                    schema='analysis'
                    )
    op.create_table('analysis_result',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis', sa.String(), nullable=False),
                    sa.Column('python_code', sa.String(), nullable=True),
                    sa.Column('output_variable', sa.String(), nullable=True),
                    sa.Column('input_variable', sa.String(), nullable=True),
                    sa.Column('section_id', sa.UUID(), nullable=True),
                    sa.Column('next_type', sa.String(), nullable=True),
                    sa.Column('next_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['section_id'], ['analysis.notebook_section.id'], name=op.f(
                        'fk_analysis_result_section_id_notebook_section')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_analysis_result')),
                    schema='analysis'
                    )
    op.create_table('dataset_from_data_source',
                    sa.Column('data_source_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_dataset_from_data_source_data_source_id_data_source')),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_dataset_from_data_source_dataset_id_dataset')),
                    sa.PrimaryKeyConstraint('data_source_id', 'dataset_id', name=op.f(
                        'pk_dataset_from_data_source')),
                    schema='data_objects'
                    )
    op.create_table('dataset_from_dataset',
                    sa.Column('source_dataset_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_dataset_from_dataset_dataset_id_dataset')),
                    sa.ForeignKeyConstraint(['source_dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_dataset_from_dataset_source_dataset_id_dataset')),
                    sa.PrimaryKeyConstraint(
                        'source_dataset_id', 'dataset_id', name=op.f('pk_dataset_from_dataset')),
                    schema='data_objects'
                    )
    op.create_table('dataset_from_pipeline',
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_dataset_from_pipeline_dataset_id_dataset')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_dataset_from_pipeline_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint(
                        'pipeline_id', 'dataset_id', name=op.f('pk_dataset_from_pipeline')),
                    schema='data_objects'
                    )
    op.create_table('object_group',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('original_id_name', sa.String(), nullable=True),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('structure_type', sa.String(), nullable=False),
                    sa.Column('save_path', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "structure_type IN ('time_series', 'time_series_aggregation')"),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_object_group_dataset_id_dataset')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_object_group')),
                    schema='data_objects'
                    )
    op.create_table('variable_group',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('save_path', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_variable_group_dataset_id_dataset')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_variable_group')),
                    schema='data_objects'
                    )
    op.create_table('data_source_analysis',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('data_source_id', sa.UUID(), nullable=False),
                    sa.Column('content_description',
                              sa.String(), nullable=False),
                    sa.Column('quality_description',
                              sa.String(), nullable=False),
                    sa.Column('eda_summary', sa.String(), nullable=False),
                    sa.Column('cautions', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_data_source_analysis_data_source_id_data_source')),
                    sa.ForeignKeyConstraint(['id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_data_source_analysis_id_data_source')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_data_source_analysis')),
                    schema='data_sources'
                    )
    op.create_table('tabular_file_data_source',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('file_name', sa.String(), nullable=False),
                    sa.Column('file_path', sa.String(), nullable=False),
                    sa.Column('file_type', sa.String(), nullable=False),
                    sa.Column('file_size_bytes',
                              sa.BigInteger(), nullable=False),
                    sa.Column('num_rows', sa.Integer(), nullable=False),
                    sa.Column('num_columns', sa.Integer(), nullable=False),
                    sa.Column('content_preview', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_tabular_file_data_source_id_data_source')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_tabular_file_data_source')),
                    schema='data_sources'
                    )
    op.create_table('function_input_object_group_definition',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('structure_id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('required', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "structure_id IN ('time_series', 'time_series_aggregation')"),
                    sa.ForeignKeyConstraint(['function_id'], ['function.function.id'], name=op.f(
                        'fk_function_input_object_group_definition_function_id_function')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_function_input_object_group_definition')),
                    sa.UniqueConstraint('function_id', 'name', name=op.f(
                        'uq_function_input_object_group_definition_function_id')),
                    schema='function'
                    )
    op.create_table('function_output_object_group_definition',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('output_entity_id_name',
                              sa.String(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('structure_id', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "structure_id IN ('time_series', 'time_series_aggregation')"),
                    sa.ForeignKeyConstraint(['function_id'], ['function.function.id'], name=op.f(
                        'fk_function_output_object_group_definition_function_id_function')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_function_output_object_group_definition')),
                    sa.UniqueConstraint('function_id', 'name', name=op.f(
                        'uq_function_output_object_group_definition_function_id')),
                    schema='function'
                    )
    op.create_table('model',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('definition_id', sa.UUID(), nullable=False),
                    sa.Column('filename', sa.String(), nullable=False),
                    sa.Column('python_class_name',
                              sa.String(), nullable=False),
                    sa.Column('module_path', sa.String(), nullable=False),
                    sa.Column('version', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('newest_update_description',
                              sa.String(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=1536), nullable=False),
                    sa.Column('source_id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('config_schema', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('default_config', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('programming_language_with_version',
                              sa.String(), nullable=False),
                    sa.Column('implementation_script_path',
                              sa.String(), nullable=False),
                    sa.Column('setup_script_path', sa.String(), nullable=True),
                    sa.Column('model_class_docstring',
                              sa.String(), nullable=False),
                    sa.Column('training_function_id',
                              sa.UUID(), nullable=False),
                    sa.Column('inference_function_id',
                              sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['definition_id'], ['model.model_definition.id'], name=op.f(
                        'fk_model_definition_id_model_definition')),
                    sa.ForeignKeyConstraint(['inference_function_id'], ['model.model_function.id'], name=op.f(
                        'fk_model_inference_function_id_model_function')),
                    sa.ForeignKeyConstraint(['source_id'], ['model_sources.model_source.id'], name=op.f(
                        'fk_model_source_id_model_source')),
                    sa.ForeignKeyConstraint(['training_function_id'], ['model.model_function.id'], name=op.f(
                        'fk_model_training_function_id_model_function')),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['auth.users.id'], name=op.f('fk_model_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_model')),
                    schema='model'
                    )
    op.create_table('pypi_model_source',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('package_name', sa.String(), nullable=False),
                    sa.Column('package_version', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['model_sources.model_source.id'], name=op.f(
                        'fk_pypi_model_source_id_model_source')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_pypi_model_source')),
                    schema='model_sources'
                    )
    op.create_table('node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('x_position', sa.Float(), nullable=False),
                    sa.Column('y_position', sa.Float(), nullable=False),
                    sa.Column('type', sa.String(length=255), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_node_project_id_project')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_node')),
                    schema='node'
                    )
    op.create_table('conversation',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_conversation_project_id_project')),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f(
                        'fk_conversation_user_id_users')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_conversation')),
                    schema='orchestrator'
                    )
    op.create_table('data_source_context',
                    sa.Column('context_id', sa.UUID(), nullable=False),
                    sa.Column('data_source_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['context_id'], ['orchestrator.chat_context.id'], name=op.f(
                        'fk_data_source_context_context_id_chat_context')),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_data_source_context_data_source_id_data_source')),
                    sa.PrimaryKeyConstraint(
                        'context_id', 'data_source_id', name=op.f('pk_data_source_context')),
                    schema='orchestrator'
                    )
    op.create_table('dataset_context',
                    sa.Column('context_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['context_id'], ['orchestrator.chat_context.id'], name=op.f(
                        'fk_dataset_context_context_id_chat_context')),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_dataset_context_dataset_id_dataset')),
                    sa.PrimaryKeyConstraint(
                        'context_id', 'dataset_id', name=op.f('pk_dataset_context')),
                    schema='orchestrator'
                    )
    op.create_table('pipeline_context',
                    sa.Column('context_id', sa.UUID(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['context_id'], ['orchestrator.chat_context.id'], name=op.f(
                        'fk_pipeline_context_context_id_chat_context')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_pipeline_context_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint(
                        'context_id', 'pipeline_id', name=op.f('pk_pipeline_context')),
                    schema='orchestrator'
                    )
    op.create_table('function_in_pipeline',
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['function_id'], ['function.function.id'], name=op.f(
                        'fk_function_in_pipeline_function_id_function')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_function_in_pipeline_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint(
                        'pipeline_id', 'function_id', name=op.f('pk_function_in_pipeline')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_graph_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "type IN ('dataset', 'function', 'model_instantiated')"),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_pipeline_graph_node_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_pipeline_graph_node')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_on_event_schedule',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('event_listener_script_path',
                              sa.String(), nullable=False),
                    sa.Column('event_description',
                              sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_pipeline_on_event_schedule_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_pipeline_on_event_schedule')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_output_dataset',
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_pipeline_output_dataset_dataset_id_dataset')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_pipeline_output_dataset_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint('pipeline_id', 'dataset_id', name=op.f(
                        'pk_pipeline_output_dataset')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_output_object_group_definition',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('structure_id', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('output_entity_id_name',
                              sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "structure_id IN ('time_series', 'time_series_aggregation')"),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_pipeline_output_object_group_definition_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_pipeline_output_object_group_definition')),
                    sa.UniqueConstraint('pipeline_id', 'name', name=op.f(
                        'uq_pipeline_output_object_group_definition_pipeline_id')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_periodic_schedule',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('start_time', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('end_time', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('schedule_description',
                              sa.String(), nullable=True),
                    sa.Column('cron_expression', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_pipeline_periodic_schedule_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_pipeline_periodic_schedule')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_run',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('start_time', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('end_time', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_pipeline_run_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_pipeline_run')),
                    schema='pipeline'
                    )
    op.create_table('project_data_source',
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('data_source_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_project_data_source_data_source_id_data_source')),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_project_data_source_project_id_project')),
                    sa.PrimaryKeyConstraint(
                        'project_id', 'data_source_id', name=op.f('pk_project_data_source')),
                    schema='project'
                    )
    op.create_table('project_dataset',
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_project_dataset_dataset_id_dataset')),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_project_dataset_project_id_project')),
                    sa.PrimaryKeyConstraint(
                        'project_id', 'dataset_id', name=op.f('pk_project_dataset')),
                    schema='project'
                    )
    op.create_table('project_pipeline',
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_project_pipeline_pipeline_id_pipeline')),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_project_pipeline_project_id_project')),
                    sa.PrimaryKeyConstraint(
                        'project_id', 'pipeline_id', name=op.f('pk_project_pipeline')),
                    schema='project'
                    )
    op.create_table('analysis_result_data_source',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
                    sa.Column('data_source_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_analysis_result_data_source_analysis_result_id_analysis_result')),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_analysis_result_data_source_data_source_id_data_source')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_analysis_result_data_source')),
                    schema='analysis'
                    )
    op.create_table('analysis_result_dataset',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_analysis_result_dataset_analysis_result_id_analysis_result')),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_analysis_result_dataset_dataset_id_dataset')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_analysis_result_dataset')),
                    schema='analysis'
                    )
    op.create_table('plot',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
                    sa.Column('plot_config', sa.JSON(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_plot_analysis_result_id_analysis_result')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_plot')),
                    schema='analysis'
                    )
    op.create_table('table',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
                    sa.Column('table_config', sa.JSON(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_table_analysis_result_id_analysis_result')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_table')),
                    schema='analysis'
                    )
    op.create_table('aggregation_object',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_aggregation_object_analysis_result_id_analysis_result')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_aggregation_object')),
                    schema='data_objects'
                    )
    op.create_table('data_object',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('group_id', sa.UUID(), nullable=True),
                    sa.Column('original_id', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('structure_type', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('additional_variables', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "structure_type IN ('time_series', 'time_series_aggregation')"),
                    sa.ForeignKeyConstraint(['group_id'], ['data_objects.object_group.id'], name=op.f(
                        'fk_data_object_group_id_object_group')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_object')),
                    schema='data_objects'
                    )
    op.create_table('feature_in_group',
                    sa.Column('group_id', sa.UUID(), nullable=False),
                    sa.Column('feature_name', sa.String(), nullable=False),
                    sa.Column('source', sa.String(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint("source IN ('data', 'metadata')"),
                    sa.ForeignKeyConstraint(['feature_name'], ['data_objects.feature.name'], name=op.f(
                        'fk_feature_in_group_feature_name_feature')),
                    sa.ForeignKeyConstraint(['group_id'], ['data_objects.object_group.id'], name=op.f(
                        'fk_feature_in_group_group_id_object_group')),
                    sa.PrimaryKeyConstraint(
                        'group_id', 'feature_name', name=op.f('pk_feature_in_group')),
                    schema='data_objects'
                    )
    op.create_table('time_series_aggregation_object_group',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('time_series_aggregation_outputs_df_schema',
                              sa.String(), nullable=False),
                    sa.Column('time_series_aggregation_outputs_df_head',
                              sa.String(), nullable=False),
                    sa.Column('time_series_aggregation_inputs_df_schema',
                              sa.String(), nullable=False),
                    sa.Column('time_series_aggregation_inputs_df_head',
                              sa.String(), nullable=False),
                    sa.Column('entity_metadata_df_schema',
                              sa.String(), nullable=True),
                    sa.Column('entity_metadata_df_head',
                              sa.String(), nullable=True),
                    sa.Column('feature_information_df_schema',
                              sa.String(), nullable=True),
                    sa.Column('feature_information_df_head',
                              sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['data_objects.object_group.id'], name=op.f(
                        'fk_time_series_aggregation_object_group_id_object_group')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_time_series_aggregation_object_group')),
                    schema='data_objects'
                    )
    op.create_table('time_series_object_group',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('time_series_df_schema',
                              sa.String(), nullable=False),
                    sa.Column('time_series_df_head',
                              sa.String(), nullable=False),
                    sa.Column('entity_metadata_df_schema',
                              sa.String(), nullable=True),
                    sa.Column('entity_metadata_df_head',
                              sa.String(), nullable=True),
                    sa.Column('feature_information_df_schema',
                              sa.String(), nullable=True),
                    sa.Column('feature_information_df_head',
                              sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['data_objects.object_group.id'], name=op.f(
                        'fk_time_series_object_group_id_object_group')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_time_series_object_group')),
                    schema='data_objects'
                    )
    op.create_table('feature_in_tabular_file',
                    sa.Column('feature_name', sa.String(), nullable=False),
                    sa.Column('tabular_file_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['feature_name'], ['data_objects.feature.name'], name=op.f(
                        'fk_feature_in_tabular_file_feature_name_feature')),
                    sa.ForeignKeyConstraint(['tabular_file_id'], ['data_sources.tabular_file_data_source.id'], name=op.f(
                        'fk_feature_in_tabular_file_tabular_file_id_tabular_file_data_source')),
                    sa.PrimaryKeyConstraint('feature_name', 'tabular_file_id', name=op.f(
                        'pk_feature_in_tabular_file')),
                    schema='data_sources'
                    )
    op.create_table('model_instantiated',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('model_id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('config', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=False),
                    sa.Column('weights_save_dir', sa.String(), nullable=True),
                    sa.Column('pipeline_id', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['model_id'], ['model.model.id'], name=op.f(
                        'fk_model_entity_model_id_model')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_model_entity_pipeline_id_pipeline')),
                    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f(
                        'fk_model_entity_user_id_users')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_model_entity')),
                    schema='model'
                    )
    op.create_table('analysis_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('analysis_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.analysis_object.id'], name=op.f(
                        'fk_analysis_node_analysis_id_analysis_object')),
                    sa.ForeignKeyConstraint(
                        ['id'], ['node.node.id'], name=op.f('fk_analysis_node_id_node')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_analysis_node')),
                    schema='node'
                    )
    op.create_table('data_source_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('data_source_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_data_source_node_data_source_id_data_source')),
                    sa.ForeignKeyConstraint(['id'], ['node.node.id'], name=op.f(
                        'fk_data_source_node_id_node')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_data_source_node')),
                    schema='node'
                    )
    op.create_table('dataset_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_dataset_node_dataset_id_dataset')),
                    sa.ForeignKeyConstraint(
                        ['id'], ['node.node.id'], name=op.f('fk_dataset_node_id_node')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_dataset_node')),
                    schema='node'
                    )
    op.create_table('pipeline_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['id'], ['node.node.id'], name=op.f('fk_pipeline_node_id_node')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_pipeline_node_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_pipeline_node')),
                    schema='node'
                    )
    op.create_table('analysis_context',
                    sa.Column('context_id', sa.UUID(), nullable=False),
                    sa.Column('analysis_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.analysis_object.id'], name=op.f(
                        'fk_analysis_context_analysis_id_analysis_object')),
                    sa.ForeignKeyConstraint(['context_id'], ['orchestrator.chat_context.id'], name=op.f(
                        'fk_analysis_context_context_id_chat_context')),
                    sa.PrimaryKeyConstraint(
                        'context_id', 'analysis_id', name=op.f('pk_analysis_context')),
                    schema='orchestrator'
                    )
    op.create_table('chat_message',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('conversation_id', sa.UUID(), nullable=False),
                    sa.Column('role', sa.String(), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('context_id', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['context_id'], ['orchestrator.chat_context.id'], name=op.f(
                        'fk_chat_message_context_id_chat_context')),
                    sa.ForeignKeyConstraint(['conversation_id'], ['orchestrator.conversation.id'], name=op.f(
                        'fk_chat_message_conversation_id_conversation')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_chat_message')),
                    schema='orchestrator'
                    )
    op.create_table('chat_pydantic_message',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('conversation_id', sa.UUID(), nullable=False),
                    sa.Column('message_list', postgresql.BYTEA(),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['conversation_id'], ['orchestrator.conversation.id'], name=op.f(
                        'fk_chat_pydantic_message_conversation_id_conversation')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_chat_pydantic_message')),
                    schema='orchestrator'
                    )
    op.create_table('object_group_in_pipeline',
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('object_group_id', sa.UUID(), nullable=False),
                    sa.Column('code_variable_name',
                              sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['object_group_id'], ['data_objects.object_group.id'], name=op.f(
                        'fk_object_group_in_pipeline_object_group_id_object_group')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_object_group_in_pipeline_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint('pipeline_id', 'object_group_id', name=op.f(
                        'pk_object_group_in_pipeline')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_graph_dataset_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_pipeline_graph_dataset_node_dataset_id_dataset')),
                    sa.ForeignKeyConstraint(['id'], ['pipeline.pipeline_graph_node.id'], name=op.f(
                        'fk_pipeline_graph_dataset_node_id_pipeline_graph_node')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_pipeline_graph_dataset_node')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_graph_edge',
                    sa.Column('from_node_id', sa.UUID(), nullable=False),
                    sa.Column('to_node_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['from_node_id'], ['pipeline.pipeline_graph_node.id'], name=op.f(
                        'fk_pipeline_graph_edge_from_node_id_pipeline_graph_node')),
                    sa.ForeignKeyConstraint(['to_node_id'], ['pipeline.pipeline_graph_node.id'], name=op.f(
                        'fk_pipeline_graph_edge_to_node_id_pipeline_graph_node')),
                    sa.PrimaryKeyConstraint(
                        'from_node_id', 'to_node_id', name=op.f('pk_pipeline_graph_edge')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_graph_function_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('function_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['function_id'], ['function.function.id'], name=op.f(
                        'fk_pipeline_graph_function_node_function_id_function')),
                    sa.ForeignKeyConstraint(['id'], ['pipeline.pipeline_graph_node.id'], name=op.f(
                        'fk_pipeline_graph_function_node_id_pipeline_graph_node')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_pipeline_graph_function_node')),
                    schema='pipeline'
                    )
    op.create_table('project_analysis',
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('analysis_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.analysis_object.id'], name=op.f(
                        'fk_project_analysis_analysis_id_analysis_object')),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_project_analysis_project_id_project')),
                    sa.PrimaryKeyConstraint(
                        'project_id', 'analysis_id', name=op.f('pk_project_analysis')),
                    schema='project'
                    )
    op.create_table('run',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('conversation_id', sa.UUID(), nullable=True),
                    sa.Column('project_id', sa.UUID(), nullable=True),
                    sa.Column('parent_run_id', sa.UUID(), nullable=True),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('started_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('completed_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['conversation_id'], [
                        'orchestrator.conversation.id'], name=op.f('fk_run_conversation_id_conversation')),
                    sa.ForeignKeyConstraint(
                        ['parent_run_id'], ['runs.run.id'], name=op.f('fk_run_parent_run_id_run')),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_run_project_id_project')),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['auth.users.id'], name=op.f('fk_run_user_id_users')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_run')),
                    schema='runs'
                    )
    op.create_table('analysis_status_message',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('message', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('analysis_result_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis.analysis_result.id'], name=op.f(
                        'fk_analysis_status_message_analysis_result_id_analysis_result')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_analysis_status_message_run_id_run')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_analysis_status_message')),
                    schema='analysis'
                    )
    op.create_table('time_series',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('num_timestamps', sa.Integer(), nullable=False),
                    sa.Column('start_timestamp', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('end_timestamp', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('sampling_frequency',
                              sa.String(), nullable=False),
                    sa.Column('timezone', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['data_objects.data_object.id'], name=op.f(
                        'fk_time_series_id_data_object')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_series')),
                    schema='data_objects'
                    )
    op.create_table('time_series_aggregation',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('is_multi_series_computation',
                              sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['data_objects.data_object.id'], name=op.f(
                        'fk_time_series_aggregation_id_data_object')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_time_series_aggregation')),
                    schema='data_objects'
                    )
    op.create_table('model_instantiated_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('model_instantiated_id',
                              sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['node.node.id'], name=op.f(
                        'fk_model_entity_node_id_node')),
                    sa.ForeignKeyConstraint(['model_instantiated_id'], ['model.model_instantiated.id'], name=op.f(
                        'fk_model_entity_node_model_entity_id_model_entity')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_model_entity_node')),
                    schema='node'
                    )
    op.create_table('model_instantiated_context',
                    sa.Column('context_id', sa.UUID(), nullable=False),
                    sa.Column('model_instantiated_id',
                              sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['context_id'], ['orchestrator.chat_context.id'], name=op.f(
                        'fk_model_entity_context_context_id_chat_context')),
                    sa.ForeignKeyConstraint(['model_instantiated_id'], ['model.model_instantiated.id'], name=op.f(
                        'fk_model_entity_context_model_entity_id_model_entity')),
                    sa.PrimaryKeyConstraint(
                        'context_id', 'model_instantiated_id', name=op.f('pk_model_entity_context')),
                    schema='orchestrator'
                    )
    op.create_table('model_instantiated_in_pipeline',
                    sa.Column('model_instantiated_id',
                              sa.UUID(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('code_variable_name',
                              sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['model_instantiated_id'], ['model.model_instantiated.id'], name=op.f(
                        'fk_model_entity_in_pipeline_model_entity_id_model_entity')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_model_entity_in_pipeline_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint('model_instantiated_id', 'pipeline_id', name=op.f(
                        'pk_model_entity_in_pipeline')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_graph_model_entity_node',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('model_instantiated_id',
                              sa.UUID(), nullable=False),
                    sa.Column('function_type', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint(
                        "function_type IN ('training', 'inference')"),
                    sa.ForeignKeyConstraint(['id'], ['pipeline.pipeline_graph_node.id'], name=op.f(
                        'fk_pipeline_graph_model_entity_node_id_pipeline_graph_node')),
                    sa.ForeignKeyConstraint(['model_instantiated_id'], ['model.model_instantiated.id'], name=op.f(
                        'fk_pipeline_graph_model_entity_node_model_entity_id_model_entity')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_pipeline_graph_model_entity_node')),
                    schema='pipeline'
                    )
    op.create_table('pipeline_output_model_entity',
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('model_instantiated_id',
                              sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['model_instantiated_id'], ['model.model_instantiated.id'], name=op.f(
                        'fk_pipeline_output_model_entity_model_entity_id_model_entity')),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_pipeline_output_model_entity_pipeline_id_pipeline')),
                    sa.PrimaryKeyConstraint('pipeline_id', 'model_instantiated_id', name=op.f(
                        'pk_pipeline_output_model_entity')),
                    schema='pipeline'
                    )
    op.create_table('project_model_entity',
                    sa.Column('project_id', sa.UUID(), nullable=False),
                    sa.Column('model_instantiated_id',
                              sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['model_instantiated_id'], ['model.model_instantiated.id'], name=op.f(
                        'fk_project_model_entity_model_entity_id_model_entity')),
                    sa.ForeignKeyConstraint(['project_id'], ['project.project.id'], name=op.f(
                        'fk_project_model_entity_project_id_project')),
                    sa.PrimaryKeyConstraint(
                        'project_id', 'model_instantiated_id', name=op.f('pk_project_model_entity')),
                    schema='project'
                    )
    op.create_table('analysis_in_run',
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('analysis_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.analysis_object.id'], name=op.f(
                        'fk_analysis_in_run_analysis_id_analysis_object')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_analysis_in_run_run_id_run')),
                    sa.PrimaryKeyConstraint('run_id', 'analysis_id',
                                            name=op.f('pk_analysis_in_run')),
                    schema='runs'
                    )
    op.create_table('data_source_from_run',
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('data_source_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_data_source_from_run_data_source_id_data_source')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_data_source_from_run_run_id_run')),
                    sa.PrimaryKeyConstraint(
                        'run_id', 'data_source_id', name=op.f('pk_data_source_from_run')),
                    schema='runs'
                    )
    op.create_table('data_source_in_run',
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('data_source_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.data_source.id'], name=op.f(
                        'fk_data_source_in_run_data_source_id_data_source')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_data_source_in_run_run_id_run')),
                    sa.PrimaryKeyConstraint(
                        'run_id', 'data_source_id', name=op.f('pk_data_source_in_run')),
                    schema='runs'
                    )
    op.create_table('dataset_from_run',
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_dataset_from_run_dataset_id_dataset')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_dataset_from_run_run_id_run')),
                    sa.PrimaryKeyConstraint('run_id', 'dataset_id',
                                            name=op.f('pk_dataset_from_run')),
                    schema='runs'
                    )
    op.create_table('dataset_in_run',
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('dataset_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['dataset_id'], ['data_objects.dataset.id'], name=op.f(
                        'fk_dataset_in_run_dataset_id_dataset')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_dataset_in_run_run_id_run')),
                    sa.PrimaryKeyConstraint('run_id', 'dataset_id',
                                            name=op.f('pk_dataset_in_run')),
                    schema='runs'
                    )
    op.create_table('model_instantiated_from_run',
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('model_instantiated_id',
                              sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['model_instantiated_id'], ['model.model_instantiated.id'], name=op.f(
                        'fk_model_entity_from_run_model_entity_id_model_entity')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_model_entity_from_run_run_id_run')),
                    sa.PrimaryKeyConstraint(
                        'run_id', 'model_instantiated_id', name=op.f('pk_model_entity_from_run')),
                    schema='runs'
                    )
    op.create_table('model_instantiated_in_run',
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('model_instantiated_id',
                              sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['model_instantiated_id'], ['model.model_instantiated.id'], name=op.f(
                        'fk_model_entity_in_run_model_entity_id_model_entity')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_model_entity_in_run_run_id_run')),
                    sa.PrimaryKeyConstraint(
                        'run_id', 'model_instantiated_id', name=op.f('pk_model_entity_in_run')),
                    schema='runs'
                    )
    op.create_table('pipeline_from_run',
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_pipeline_from_run_pipeline_id_pipeline')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_pipeline_from_run_run_id_run')),
                    sa.PrimaryKeyConstraint('run_id', 'pipeline_id',
                                            name=op.f('pk_pipeline_from_run')),
                    schema='runs'
                    )
    op.create_table('pipeline_in_run',
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('pipeline_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.pipeline.id'], name=op.f(
                        'fk_pipeline_in_run_pipeline_id_pipeline')),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_pipeline_in_run_run_id_run')),
                    sa.PrimaryKeyConstraint('run_id', 'pipeline_id',
                                            name=op.f('pk_pipeline_in_run')),
                    schema='runs'
                    )
    op.create_table('run_message',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('content', sa.String(), nullable=False),
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['run_id'], ['runs.run.id'], name=op.f('fk_run_message_run_id_run')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_message')),
                    schema='runs'
                    )
    op.create_table('run_pydantic_message',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('message_list', postgresql.BYTEA(),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_run_pydantic_message_run_id_run')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_run_pydantic_message')),
                    schema='runs'
                    )
    op.create_table('run_specification',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('run_id', sa.UUID(), nullable=False),
                    sa.Column('run_name', sa.String(), nullable=False),
                    sa.Column('plan_and_deliverable_description_for_user',
                              sa.String(), nullable=False),
                    sa.Column('plan_and_deliverable_description_for_agent',
                              sa.String(), nullable=False),
                    sa.Column('questions_for_user',
                              sa.String(), nullable=True),
                    sa.Column('configuration_defaults_description',
                              sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['run_id'], ['runs.run.id'], name=op.f(
                        'fk_run_specification_run_id_run')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_run_specification')),
                    schema='runs'
                    )
    op.create_table('time_series_aggregation_input',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('time_series_id', sa.UUID(), nullable=False),
                    sa.Column('aggregation_id', sa.UUID(), nullable=False),
                    sa.Column('input_feature_name',
                              sa.String(), nullable=False),
                    sa.Column('start_timestamp', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('end_timestamp', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.CheckConstraint('start_timestamp < end_timestamp'),
                    sa.ForeignKeyConstraint(['aggregation_id'], ['data_objects.time_series_aggregation.id'], name=op.f(
                        'fk_time_series_aggregation_input_aggregation_id_time_series_aggregation')),
                    sa.ForeignKeyConstraint(['id'], ['data_objects.data_object.id'], name=op.f(
                        'fk_time_series_aggregation_input_id_data_object')),
                    sa.ForeignKeyConstraint(['time_series_id'], ['data_objects.time_series.id'], name=op.f(
                        'fk_time_series_aggregation_input_time_series_id_time_series')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk_time_series_aggregation_input')),
                    schema='data_objects'
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_series_aggregation_input', schema='data_objects')
    op.drop_table('run_specification', schema='runs')
    op.drop_table('run_pydantic_message', schema='runs')
    op.drop_table('run_message', schema='runs')
    op.drop_table('pipeline_in_run', schema='runs')
    op.drop_table('pipeline_from_run', schema='runs')
    op.drop_table('model_instantiated_in_run', schema='runs')
    op.drop_table('model_instantiated_from_run', schema='runs')
    op.drop_table('dataset_in_run', schema='runs')
    op.drop_table('dataset_from_run', schema='runs')
    op.drop_table('data_source_in_run', schema='runs')
    op.drop_table('data_source_from_run', schema='runs')
    op.drop_table('analysis_in_run', schema='runs')
    op.drop_table('project_model_entity', schema='project')
    op.drop_table('pipeline_output_model_entity', schema='pipeline')
    op.drop_table('pipeline_graph_model_entity_node', schema='pipeline')
    op.drop_table('model_instantiated_in_pipeline', schema='pipeline')
    op.drop_table('model_instantiated_context', schema='orchestrator')
    op.drop_table('model_instantiated_node', schema='node')
    op.drop_table('time_series_aggregation', schema='data_objects')
    op.drop_table('time_series', schema='data_objects')
    op.drop_table('analysis_status_message', schema='analysis')
    op.drop_table('run', schema='runs')
    op.drop_table('project_analysis', schema='project')
    op.drop_table('pipeline_graph_function_node', schema='pipeline')
    op.drop_table('pipeline_graph_edge', schema='pipeline')
    op.drop_table('pipeline_graph_dataset_node', schema='pipeline')
    op.drop_table('object_group_in_pipeline', schema='pipeline')
    op.drop_table('chat_pydantic_message', schema='orchestrator')
    op.drop_table('chat_message', schema='orchestrator')
    op.drop_table('analysis_context', schema='orchestrator')
    op.drop_table('pipeline_node', schema='node')
    op.drop_table('dataset_node', schema='node')
    op.drop_table('data_source_node', schema='node')
    op.drop_table('analysis_node', schema='node')
    op.drop_table('model_instantiated', schema='model')
    op.drop_table('feature_in_tabular_file', schema='data_sources')
    op.drop_table('time_series_object_group', schema='data_objects')
    op.drop_table('time_series_aggregation_object_group',
                  schema='data_objects')
    op.drop_table('feature_in_group', schema='data_objects')
    op.drop_table('data_object', schema='data_objects')
    op.drop_table('aggregation_object', schema='data_objects')
    op.drop_table('table', schema='analysis')
    op.drop_table('plot', schema='analysis')
    op.drop_table('analysis_result_dataset', schema='analysis')
    op.drop_table('analysis_result_data_source', schema='analysis')
    op.drop_table('project_pipeline', schema='project')
    op.drop_table('project_dataset', schema='project')
    op.drop_table('project_data_source', schema='project')
    op.drop_table('pipeline_run', schema='pipeline')
    op.drop_table('pipeline_periodic_schedule', schema='pipeline')
    op.drop_table('pipeline_output_object_group_definition', schema='pipeline')
    op.drop_table('pipeline_output_dataset', schema='pipeline')
    op.drop_table('pipeline_on_event_schedule', schema='pipeline')
    op.drop_table('pipeline_graph_node', schema='pipeline')
    op.drop_table('function_in_pipeline', schema='pipeline')
    op.drop_table('pipeline_context', schema='orchestrator')
    op.drop_table('dataset_context', schema='orchestrator')
    op.drop_table('data_source_context', schema='orchestrator')
    op.drop_table('conversation', schema='orchestrator')
    op.drop_table('node', schema='node')
    op.drop_table('pypi_model_source', schema='model_sources')
    op.drop_table('model', schema='model')
    op.drop_table('function_output_object_group_definition', schema='function')
    op.drop_table('function_input_object_group_definition', schema='function')
    op.drop_table('tabular_file_data_source', schema='data_sources')
    op.drop_table('data_source_analysis', schema='data_sources')
    op.drop_table('variable_group', schema='data_objects')
    op.drop_table('object_group', schema='data_objects')
    op.drop_table('dataset_from_pipeline', schema='data_objects')
    op.drop_table('dataset_from_dataset', schema='data_objects')
    op.drop_table('dataset_from_data_source', schema='data_objects')
    op.drop_table('analysis_result', schema='analysis')
    op.drop_table('analysis_object', schema='analysis')
    op.drop_table('project', schema='project')
    op.drop_table('pipeline', schema='pipeline')
    op.drop_table('model_source', schema='model_sources')
    op.drop_table(
        'model_function_output_object_group_definition', schema='model')
    op.drop_table('model_function_input_object_group_definition',
                  schema='model')
    op.drop_table('function', schema='function')
    op.drop_table('data_source', schema='data_sources')
    op.drop_table('dataset', schema='data_objects')
    op.drop_table('user_api_keys', schema='auth')
    op.drop_table('notebook_section', schema='analysis')
    op.drop_table('chat_context', schema='orchestrator')
    op.drop_table('model_function', schema='model')
    op.drop_table('model_definition', schema='model')
    op.drop_table('function_definition', schema='function')
    op.drop_table('feature', schema='data_objects')
    op.drop_table('users', schema='auth')
    op.drop_table('notebook', schema='analysis')
    # ### end Alembic commands ###
