"""Remove data source type constraint

Revision ID: cf5b591bf138
Revises: 44cc4edd8392
Create Date: 2025-10-19 19:22:52.287504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5b591bf138'
down_revision: Union[str, None] = '44cc4edd8392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the check constraint on the type column
    op.drop_constraint('data_source_type_check', 'data_source',
                       schema='data_sources', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the check constraint on the type column
    op.create_check_constraint(
        'data_source_type_check',
        'data_source',
        "type IN ('file')",
        schema='data_sources'
    )
    # ### end Alembic commands ###
