"""Add read raw data fn name field

Revision ID: cfaefc59671b
Revises: b3c631731929
Create Date: 2025-11-04 16:49:30.587260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfaefc59671b'
down_revision: Union[str, None] = 'b3c631731929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_group', sa.Column('raw_data_read_function_name', sa.String(), nullable=True), schema='data_objects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_group', 'raw_data_read_function_name', schema='data_objects')
    # ### end Alembic commands ###
