"""Add docstrings and refactor function / model full and bare

Revision ID: dab598d74ca0
Revises: 1395dce1fae3
Create Date: 2025-10-03 03:13:18.229581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab598d74ca0'
down_revision: Union[str, None] = '1395dce1fae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function', sa.Column('docstring', sa.String(), nullable=False), schema='function')
    op.add_column('model', sa.Column('implementation_description', sa.String(), nullable=False), schema='model')
    op.add_column('model', sa.Column('model_class_docstring', sa.String(), nullable=False), schema='model')
    op.add_column('model', sa.Column('training_function_docstring', sa.String(), nullable=False), schema='model')
    op.add_column('model', sa.Column('inference_function_docstring', sa.String(), nullable=False), schema='model')
    op.add_column('pipeline', sa.Column('docstring', sa.String(), nullable=False), schema='pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline', 'docstring', schema='pipeline')
    op.drop_column('model', 'inference_function_docstring', schema='model')
    op.drop_column('model', 'training_function_docstring', schema='model')
    op.drop_column('model', 'model_class_docstring', schema='model')
    op.drop_column('model', 'implementation_description', schema='model')
    op.drop_column('function', 'docstring', schema='function')
    # ### end Alembic commands ###
