"""Rename analysis object to analysis

Revision ID: ed1510f9d137
Revises: 27e22eacdf28
Create Date: 2025-10-22 04:26:47.376131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed1510f9d137'
down_revision: Union[str, None] = '27e22eacdf28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the table
    op.rename_table('analysis_object', 'analysis', schema='analysis')

    # Rename primary key constraint
    op.execute(
        'ALTER TABLE analysis.analysis RENAME CONSTRAINT pk_analysis_object TO pk_analysis')

    # Rename foreign key constraint
    op.execute('ALTER TABLE analysis.analysis RENAME CONSTRAINT fk_analysis_object_user_id_users TO fk_analysis_user_id_users')
    op.add_column('data_source_in_analysis', sa.Column(
        'analysis_id', sa.UUID(), nullable=False), schema='analysis')
    op.drop_constraint(op.f('fk_data_source_in_analysis_analysis_object_id_analysis_object'),
                       'data_source_in_analysis', schema='analysis', type_='foreignkey')
    op.create_foreign_key(op.f('fk_data_source_in_analysis_analysis_id_analysis'), 'data_source_in_analysis', 'analysis', [
                          'analysis_id'], ['id'], source_schema='analysis', referent_schema='analysis')
    op.drop_column('data_source_in_analysis',
                   'analysis_object_id', schema='analysis')
    op.add_column('dataset_in_analysis', sa.Column(
        'analysis_id', sa.UUID(), nullable=False), schema='analysis')
    op.drop_constraint(op.f('fk_dataset_in_analysis_analysis_object_id_analysis_object'),
                       'dataset_in_analysis', schema='analysis', type_='foreignkey')
    op.create_foreign_key(op.f('fk_dataset_in_analysis_analysis_id_analysis'), 'dataset_in_analysis', 'analysis', [
                          'analysis_id'], ['id'], source_schema='analysis', referent_schema='analysis')
    op.drop_column('dataset_in_analysis',
                   'analysis_object_id', schema='analysis')
    op.add_column('model_entity_in_analysis', sa.Column(
        'analysis_id', sa.UUID(), nullable=False), schema='analysis')
    op.drop_constraint(op.f('fk_model_entity_in_analysis_analysis_object_id_analysis_object'),
                       'model_entity_in_analysis', schema='analysis', type_='foreignkey')
    op.create_foreign_key(op.f('fk_model_entity_in_analysis_analysis_id_analysis'), 'model_entity_in_analysis', 'analysis', [
                          'analysis_id'], ['id'], source_schema='analysis', referent_schema='analysis')
    op.drop_column('model_entity_in_analysis',
                   'analysis_object_id', schema='analysis')
    op.drop_constraint(op.f('fk_analysis_context_analysis_id_analysis_object'),
                       'analysis_context', schema='orchestrator', type_='foreignkey')
    op.create_foreign_key(op.f('fk_analysis_context_analysis_id_analysis'), 'analysis_context', 'analysis', [
                          'analysis_id'], ['id'], source_schema='orchestrator', referent_schema='analysis')
    op.drop_constraint(op.f('fk_project_analysis_analysis_id_analysis_object'),
                       'project_analysis', schema='project', type_='foreignkey')
    op.create_foreign_key(op.f('fk_project_analysis_analysis_id_analysis'), 'project_analysis', 'analysis', [
                          'analysis_id'], ['id'], source_schema='project', referent_schema='analysis')
    op.drop_constraint(op.f('fk_analysis_from_run_analysis_id_analysis_object'),
                       'analysis_from_run', schema='runs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_analysis_from_run_analysis_id_analysis'), 'analysis_from_run', 'analysis', [
                          'analysis_id'], ['id'], source_schema='runs', referent_schema='analysis')
    op.drop_constraint(op.f('fk_analysis_in_run_analysis_id_analysis_object'),
                       'analysis_in_run', schema='runs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_analysis_in_run_analysis_id_analysis'), 'analysis_in_run', 'analysis', [
                          'analysis_id'], ['id'], source_schema='runs', referent_schema='analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_analysis_in_run_analysis_id_analysis'),
                       'analysis_in_run', schema='runs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_analysis_in_run_analysis_id_analysis_object'), 'analysis_in_run', 'analysis_object', [
                          'analysis_id'], ['id'], source_schema='runs', referent_schema='analysis')
    op.drop_constraint(op.f('fk_analysis_from_run_analysis_id_analysis'),
                       'analysis_from_run', schema='runs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_analysis_from_run_analysis_id_analysis_object'), 'analysis_from_run', 'analysis_object', [
                          'analysis_id'], ['id'], source_schema='runs', referent_schema='analysis')
    op.drop_constraint(op.f('fk_project_analysis_analysis_id_analysis'),
                       'project_analysis', schema='project', type_='foreignkey')
    op.create_foreign_key(op.f('fk_project_analysis_analysis_id_analysis_object'), 'project_analysis', 'analysis_object', [
                          'analysis_id'], ['id'], source_schema='project', referent_schema='analysis')
    op.drop_constraint(op.f('fk_analysis_context_analysis_id_analysis'),
                       'analysis_context', schema='orchestrator', type_='foreignkey')
    op.create_foreign_key(op.f('fk_analysis_context_analysis_id_analysis_object'), 'analysis_context', 'analysis_object', [
                          'analysis_id'], ['id'], source_schema='orchestrator', referent_schema='analysis')
    op.add_column('model_entity_in_analysis', sa.Column('analysis_object_id', sa.UUID(
    ), autoincrement=False, nullable=False), schema='analysis')
    op.drop_constraint(op.f('fk_model_entity_in_analysis_analysis_id_analysis'),
                       'model_entity_in_analysis', schema='analysis', type_='foreignkey')
    op.create_foreign_key(op.f('fk_model_entity_in_analysis_analysis_object_id_analysis_object'), 'model_entity_in_analysis',
                          'analysis_object', ['analysis_object_id'], ['id'], source_schema='analysis', referent_schema='analysis')
    op.drop_column('model_entity_in_analysis',
                   'analysis_id', schema='analysis')
    op.add_column('dataset_in_analysis', sa.Column('analysis_object_id', sa.UUID(
    ), autoincrement=False, nullable=False), schema='analysis')
    op.drop_constraint(op.f('fk_dataset_in_analysis_analysis_id_analysis'),
                       'dataset_in_analysis', schema='analysis', type_='foreignkey')
    op.create_foreign_key(op.f('fk_dataset_in_analysis_analysis_object_id_analysis_object'), 'dataset_in_analysis', 'analysis_object', [
                          'analysis_object_id'], ['id'], source_schema='analysis', referent_schema='analysis')
    op.drop_column('dataset_in_analysis', 'analysis_id', schema='analysis')
    op.add_column('data_source_in_analysis', sa.Column('analysis_object_id', sa.UUID(
    ), autoincrement=False, nullable=False), schema='analysis')
    op.drop_constraint(op.f('fk_data_source_in_analysis_analysis_id_analysis'),
                       'data_source_in_analysis', schema='analysis', type_='foreignkey')
    op.create_foreign_key(op.f('fk_data_source_in_analysis_analysis_object_id_analysis_object'), 'data_source_in_analysis',
                          'analysis_object', ['analysis_object_id'], ['id'], source_schema='analysis', referent_schema='analysis')
    op.drop_column('data_source_in_analysis', 'analysis_id', schema='analysis')

    # Rename foreign key constraint back
    op.execute('ALTER TABLE analysis.analysis RENAME CONSTRAINT fk_analysis_user_id_users TO fk_analysis_object_user_id_users')

    # Rename primary key constraint back
    op.execute(
        'ALTER TABLE analysis.analysis RENAME CONSTRAINT pk_analysis TO pk_analysis_object')

    # Rename the table back
    op.rename_table('analysis', 'analysis_object', schema='analysis')
    # ### end Alembic commands ###
