"""Remove project id from analysis obj

Revision ID: f36a7b4421c9
Revises: 2700912e8ff1
Create Date: 2025-10-21 19:38:24.121712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36a7b4421c9'
down_revision: Union[str, None] = '2700912e8ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_analysis_object_project_id_project'),
                       'analysis_object', schema='analysis', type_='foreignkey')
    op.drop_column('analysis_object', 'project_id', schema='analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_object', sa.Column('project_id', sa.UUID(
    ), autoincrement=False, nullable=False), schema='analysis')
    op.create_foreign_key(op.f('fk_analysis_object_project_id_project'), 'analysis_object', 'project', [
                          'project_id'], ['id'], source_schema='analysis', referent_schema='project')
    # ### end Alembic commands ###
