from synesis_api.agents.data_integration.local_agent.agent import local_integration_agent, LocalIntegrationDeps
from synesis_api.agents.data_integration.target_structures import TIME_SERIES_TARGET_STRUCTURE
