

TOOL_DESCRIPTIONS = {
    "write_file": "Writing new script file",
    "read_file": "Reading script",
    "replace_file_lines": "Modifying script lines",
    "add_file_lines": "Adding new lines to script",
    "delete_file_lines": "Deleting lines from script",
    "delete_file": "Deleting script file",
    "rename_file": "Renaming script file",
    "search_through_datasets": "Searching through datasets",
    "search_through_data_sources": "Searching through data sources",
    "search_through_analyses": "Searching through analyses",
    "search_through_analysis_results": "Searching through analysis results",
    "search_knowledge_bank": "Searching knowledge bank",
    "add_analysis_result_to_notebook_section": "Adding analysis result to section",
    "create_notebook_section": "Creating notebook section",
    "move_analysis_result": "Moving analysis result to section",
    "delete_notebook_section": "Deleting notebook section",
    "edit_section_name": "Editing section name",
    "move_sections": "Moving section",
    "create_empty_analysis_result": "Setting up analysis",
    "generate_analysis_result": "Generating and running code",
    "plot_analysis_result": "Plotting analysis result",
    "create_table_for_analysis_result": "Creating table for analysis result",
}
