# NB: Assumes build context is the root of the project (where the docker-compose file is).

FROM python:3.13-slim

WORKDIR /app

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt-get update \
    && apt-get install -y docker-ce-cli \
    && rm -rf /var/lib/apt/lists/*

# Copy the data_structures package first for better caching
COPY schemas /app/schemas

COPY data_structures /app/data_structures

# Copy sandbox pyproject toml to enable reading its dependencies in the SWE agent
COPY project_server/sandbox/pyproject.toml /app/sandbox/pyproject.toml

# Copy the project_server project files
COPY project_server/server /app

# Install synesis data structures package from source and the main package
RUN pip install --upgrade pip && \
    pip install -e /app/data_structures && \
    pip install -e /app/schemas && \
    pip install -e .

CMD ["uvicorn", "src.project_server.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"] 