"""Add cron run schedule to pipeline

Revision ID: 10bb84b0a015
Revises: 31da6f277b72
Create Date: 2025-08-26 10:27:06.228472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10bb84b0a015'
down_revision: Union[str, None] = '31da6f277b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('schedule', sa.String(), nullable=False), schema='pipeline')
    op.add_column('pipeline', sa.Column('cron_schedule', sa.String(), nullable=True), schema='pipeline')
    op.drop_column('pipeline', 'run_schedule', schema='pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('run_schedule', sa.VARCHAR(), autoincrement=False, nullable=True), schema='pipeline')
    op.drop_column('pipeline', 'cron_schedule', schema='pipeline')
    op.drop_column('pipeline', 'schedule', schema='pipeline')
    # ### end Alembic commands ###
