FROM python:3.12-slim

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive

COPY data_interface /app/data_interface

COPY schemas /app/schemas

# Copy the api project files
COPY main_server/server /app

# Install synesis data structures package from source and the main package
RUN pip install --upgrade pip && \
    pip install -e /app/data_interface && \
    pip install -e /app/schemas && \
    pip install -e .

CMD ["uvicorn", "src.synesis_api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]