FROM python:3.12-slim

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive

# Copy the api project files
COPY kvasir-app/main_server/server /app/server
COPY kvasir-research /app/kvasir-research
COPY kvasir-ontology /app/kvasir-ontology

# Install synesis data structures package from source and the main package
RUN pip install --upgrade pip && \
    pip install -e /app/server && \
    pip install -e /app/kvasir-research && \
    pip install -e /app/kvasir-ontology

CMD ["uvicorn", "src.synesis_api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]