from synesis_api.modules.integration.agent.local_agent.agent import local_integration_agent, LocalIntegrationDeps
from synesis_api.modules.integration.agent.prompt import TIME_SERIES_TARGET_STRUCTURE
